### ISSUE TITLE
Feature Request - Initialize "Move to Resource" with last selected resource

### ISSUE THREAD

**Issue by dasdandre** [dotnet/ResXResourceManager#129]
When using the "Move to Resource" feature multiple times **within the same source-file**, it would be very helpfull to have it initialized with the last selected resource (resx file).

**Comment by JohanLarsson** [comment]
This analyzer has a move to resource fix: https://www.nuget.org/packages/Gu.Localization.Analyzers/0.2.0.8-dev

Maybe we can use the code in this extension.

**Comment by tom-englert** [comment]
@dasdandre currently it does, however if one assembly has a resource file, this is always on top. 
The assumption is that if an assembly has a resource file, it's probably the one you want to use, and if not having the local resource but the last used as default, it's very likely that you move the resources to the wrong location when using it from code in another assembly.

The one that you used the last time is in the second slot, so just hit the down key once to get there.

**Comment by tom-englert** [comment]
@dasdandre the WinForms designer generated resource files will not be listed, so if you have just one Messages resource file, where is the conflict?

**Comment by dasdandre** [comment]
@tom-englert this was just for example, sorry. Beneath the translation directory there are other files like "Enums.resx", "ColumnNames.resx" and so on. I think it is not uncommon to group resources in this way.

**Comment by tom-englert** [comment]
@dasdandre  And you have this structure inside every project?

**Comment by dasdandre** [comment]
@tom-englert No, not in general. Our solution consist of 36 Projects. If a string is used very often (lets say a column-name) it will end up in a public resource ...Shared/Translation/Columns.resx for example. If it is a very specific column it will be part of a project ...SpecialPlugin/Translation/Columns.resx.

How about a checkbox "Remember selection" next to the resource combo-box.

**Comment by tom-englert** [comment]
@dasdandre I did some improvements on this. If the last selection was cross-project, it will remember it always, since it assumes cross-project is intended.

Can you try the latest version from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by dasdandre** [comment]
@tom-englert Works perfectly. Thank you very much.
