### ISSUE TITLE
New language not visible in Excel

### ISSUE THREAD

**Issue by jerone** [dotnet/ResXResourceManager#179]
**STRP**:
1. Open ResXResourceManager
2. Click "Add new language" and choose any new language
3. Click "Export all" option

**Expected** to see an extra column for the new language in the Excel export.

**Actual result** is only the previous languages are shown in the Excel export.

**Comment by tom-englert** [comment]
Did you add any content for the new language?

**Comment by jerone** [comment]
No, I did not, because no translation was done yet.
