### ISSUE TITLE
Please add support for Xliff 1.2 and 2.0.

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/ResXResourceManager#215]
The program is really very good, and really well integrated into Visual Studio. Unfortunately, I had to find out that in future projects I almost only use Xliff. Unfortunately I can't use the tool for this, and the tools that are available either cost a bit, or have a reduced functionality.

So I thought I'd just ask if it would be possible to add the Xliff derivatives to this powerful tool in the future. It would be great if at least Xliff 1.2 and 2.X would be supported.

**Comment by tom-englert** [comment]
This is similar to #31, you can easily generate any transform by using the text-template feature.
If you share your result, I can integrate this to the standard.

**Comment by GeertvanHorrik** [comment]
I think this is implemented now?

**Comment by tom-englert** [comment]
@GeertvanHorrik at least Xliff 1.2 is there; does anyone need 2.X?
