### ISSUE TITLE
Automatically added the BOM

### ISSUE THREAD

**Issue by haunguyen84** [dotnet/ResXResourceManager#233]
Dear Tom,
The problem is that a BOM is added automatically when editing a _Unicode_ resx file.
But it does not, when using the default resx editor of VS.
Could you please share some hint where load/read the resx file into the ResXResourceManager?

Thanks and best regards!
Hau Nguyen.

**Comment by tom-englert** [comment]
It's done here:
https://github.com/tom-englert/ResXResourceManager/blob/fec48a125dc6bc79695c8bccfd1f4c1e8ce2f83e/ResXManager.Model/ProjectFile.cs#L103-L106
As you see it's all up to `XDocument`, so if you don't like this behavior, you have to raise an issue with DotNet framework.

**Comment by denisvitez** [comment]
For UTF-8 you can use XmlWritterSettings to override the encoding. I have no idea about the Unicode and BOM though.
[SO post](https://stackoverflow.com/questions/4942825/xdocument-saving-xml-to-file-without-bom)

**Comment by taoyouh** [comment]
@haunguyen84 
In my Visual Studio 2017 15.9.12 resx editor:
1. Newly created resx files have BOM
2. UTF-8 files won't have BOM added or removed when saving
3. Files with other encodings (such as GBK) will have the encoding header changed to "utf-8", but the file content is left unchanged (so the file is corrupted)

I think it is a weird behavior. As BOM is allowed in XML, and BOM is the default file format of VS resx files, and BOM prevents many encoding problems in Windows, I think the current file saving is best and we don't need to follow this weird behavior of Visual Studio.

**Comment by haunguyen84** [comment]
I would like to update the source code for the InternalSave method as recommended by denisvitez.
Could you please grant access for me to create branch/commit?
Thanks!

**Comment by tom-englert** [comment]
@haunguyen84 what about @taoyouh comments? You seem to be the only one among many thousands of users complaining about this.

Anyway, just follow the standard workflow to provide a PR.

**Comment by haunguyen84** [comment]
Due to permission, I cannot create a branch.
remote: Permission to tom-englert/ResXResourceManager.git denied to haunguyen84.
fatal: unable to access 'https://github.com/tom-englert/ResXResourceManager.git/': The requested URL returned error: 403

**Comment by taoyouh** [comment]
You need to fork it first.

**Comment by haunguyen84** [comment]
Done: https://github.com/tom-englert/ResXResourceManager/pull/238
Thanks a lot!

**Comment by dvdduy** [comment]
> @haunguyen84
> In my Visual Studio 2017 15.9.12 resx editor:
> 
> 1. Newly created resx files have BOM
> 2. UTF-8 files won't have BOM added or removed when saving
> 3. Files with other encodings (such as GBK) will have the encoding header changed to "utf-8", but the file content is left unchanged (so the file is corrupted)
> 
> I think it is a weird behavior. As BOM is allowed in XML, and BOM is the default file format of VS resx files, and BOM prevents many encoding problems in Windows, I think the current file saving is best and we don't need to follow this weird behavior of Visual Studio.

Hi @taoyouh,
It is absolutely good with your scenario because default encoding of resource file which created by Visual Studio is UTF-8 with BOM. Unfortunately, current code of loading/saving resource file can change encoding of the resource file. Below is the current code we are using to load and save resource file in the ResXResourceManager. If the input file is in UTF-8 encoding, the saved file will be in UTF-8 with BOM encoding.

```C#
var pathFile = ...;
var doc = XDocument.Load(pathFile);
doc.Save(pathFile);
```
