### ISSUE TITLE
Can't make T4 template work with .NET Core project

### ISSUE THREAD

**Issue by mlessd** [dotnet/ResXResourceManager#290]
Hello,
Does the extension work with .NET Core projects? It keeps crashing for me.  It works in .NET Framework projects. Thanks for your help!

- Open VS (16.4.2)
- Create new project (.NET Core console app)
- Add new item, resource file
- Add a few items to the resource file
- Tools -> ResxManager
- Right-click on Resource1.resx, Code generator -> text template

The .t4 is added to Solution Items
a .tt file is added to the .resx
But the code generation fails with these 2 errors, and when I go back to Tools -> ResxManager, the options under Code generator are unavailable.

Custom tool TextTemplatingFileGenerator failed to produce an output for input file 'Resource1.Designer.tt' but did not log a specific error

Running transformation: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'EnvDTE.ProjectItem'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0B48100A-473E-433C-AB8F-66B9739AB620}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.TextTemplating5D7863637B1158E0CD80A2C232E59B544ADD7311E010D800F5C1860EBCDD72CE217E1557A9255C74FB01A3444753862A891FAD55608A127C643072169D5F8C46.GeneratedTextTransformation.GetResxProjectItem()
   at Microsoft.VisualStudio.TextTemplating5D7863637B1158E0CD80A2C232E59B544ADD7311E010D800F5C1860EBCDD72CE217E1557A9255C74FB01A3444753862A891FAD55608A127C643072169D5F8C46.GeneratedTextTransformation.TransformText()	ConsoleApp1	[...]\Resource1.Designer.tt	1

**Comment by tom-englert** [comment]
This is a known limitation of VS, see #240

**Comment by AlexanderKot** [comment]
Hello 
I have opened bug about same problem for VS
See responce
https://developercommunity.visualstudio.com/content/problem/887505/systeminvalidcastexception-unable-to-cast-com-obje-1.html

**Comment by tom-englert** [comment]
@AlexanderKot 
This is not really releated to the problem, there is nothing wrong with the text template.
The template expects being nested, so if it's not, the cast of the parent object obviously fails.
The root cause of this is https://github.com/dotnet/project-system/issues/1870.
After adding the items nesting manually (see https://github.com/tom-englert/ResXResourceManager/issues/240), it works fine again.

**Comment by mlessd** [comment]
It works after fixing the .csproj manually. Do you think it would be a good idea to find the resx file by location and name in the case where the .tt has no parent? Or maybe detect this in the .t4 and output a clear error... Thanks!

**Comment by HrlecMatej** [comment]
I am using VS 16.7.3, end the issue still persists: *.tt file does not get nested under *.resx file, which makes the template generator fail.
