### ISSUE TITLE
ResX crashing Visual Studio 2019 when adding resource files

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/ResXResourceManager#306]
"Apply All" in the translation tab, when no resource files for multiple languages are created yet, ResX asks if I want to create one, confirm it for each  language, sooner or later DevEnv.exe disappears, no message.

Seems that the resource files are created and even modified with the translations but adding them to the project crashes VS (sometimes). When I restart VS, open ResX, go to the resource and language last added, it doesnt show to have a resource file, but when I click on the field, the resource file is added and loaded.

Will see if I can get a crash dump somehow.

Project is VB with 7 languages added.

**Comment by tom-englert** [comment]
If VS crashes when adding a new resource file, it's probably an issue with VS, not ResXManager.

**Comment by tom-englert** [comment]
@Hefaistos68 any chance to narrow down this?

**Comment by Hefaistos68** [comment]
Am off this project for the moment, but will test again when I have time. Give me a few days.

**Comment by tom-englert** [comment]
Closed as stale

**Comment by NaymDev** [comment]
Hi, I have the same issue with VS2022. When I right-click on my project and select "Add Resource," Visual Studio freezes and then crashes. Unfortunately, I couldn't find any helpful resources about this online.

**Comment by tom-englert** [comment]
@NaymDev and what makes you think that is caused by RXRM?

**Comment by NaymDev** [comment]
Oh right sorry, I kinda missed the topic. I don't think it's caused by RXRM. I just was wondering if there's a fix few years later or if we can't use it.

**Comment by tom-englert** [comment]
Did someone ever report this to Microsoft?
