### ISSUE TITLE
Only 1 language at the same time

### ISSUE THREAD

**Issue by byte7-ra** [dotnet/ResXResourceManager#307]
Hello,

i have a lot of apps with over 40 languages. since 1 month i can only translate 1 language at the same time by google api. thats very strange and killes my workflow. is there any restriction or something in the script?

**Comment by tom-englert** [comment]
Sorry, RXRM only forwards the request, you have to raise this issue with Google what's up with your account

**Comment by tom-englert** [comment]
@byte7-ra did you solve your problem with Google?

**Comment by byte7-ra** [comment]
It still doesn't work. we have deinstall visual studio and reinstall it. but still have problems. ps: other apis have the same problem.

**Comment by tom-englert** [comment]
>  i can only translate 1 language at the same time

What exactly does this mean?

**Comment by byte7-ra** [comment]
Ach sehe gerade, das du auch aus Deutschland kommt. Schreibe es dann in Deutsch. So also im Grunde hab ich das Problem:
Ich hab 20 Sprachen drin. Wenn ich z.B. 5 Keys hinzufüge und die übersetzt haben will, dann schickt er immer nur eine Sprache ab mit allen 5 Keys. Danach stopt er, warum auch immer. Gibt es da ein Log oder sowas? Ich sammel jetzt schon immer mehrere Keys, damit ich nicht 20 mal am tag das machen muss und das nervt etwas. Ich weiss, du kannst da nix führ.

Meine Hoffnung ist, das es irgendwo eine Log gibt der Abfragen und irgendwo ein Error steht oder sowas in der Art. Ist mit allen APIs so.

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/78361635-01557a00-75b9-11ea-90a9-2a7f543dbe3c.png)
Also eventuelle Fehler werden unten links angezeigt. 
Bei mir übersetzt er mehrere Sprachen mit mehreren Services problemlos. 
Im zweifelsfalle einfach mal im Debugger laufen lassen...

**Comment by nullfield** [comment]
I've been having the same issue. Today I ran the standalone application in Visual Studio debugger. It indicates the issue is in project ResXManager.Translaters file GoogleTranslator.cs on line 74.

Changing the code to the following results in the second language of my project being translated:

var sourceItems = itemsEnumerator.Take(10);
if (translationSession.IsCanceled || !sourceItems.Any())
    //return; // <-- This is the original line 74
    break; // <-- This is the needed change
