### ISSUE TITLE
Excel import problem

### ISSUE THREAD

**Issue by jfquarto** [dotnet/ResXResourceManager#308]
I use ResXManager v1.40.3444 as extension in Visual Studio 2017 Pro. 
I have exported my resources successfully via the Excel option in ResXManager.
Now I tried to import the translated excel file.
For a short moment I see a "busy" cursor but nothing happens, also no errormessages.
What could be the case ?

**Comment by tom-englert** [comment]
What has changed in the Excel file?

**Comment by jfquarto** [comment]
Only some texts were translated, the structure should have stayed the same afaik.


​___
​
​Jouw twaalfde man,​
Johan Fontijne
Software developer
+31 182 700 500
Westbaan 200
​2841 MC Moordrecht
www.twelve.eu
​Wij heten vanaf nu Twelve!
​Na de overname van Quarto in 2018 zijn we nu officieel één bedrijf!
​Mocht je nog vragen hebben dan staan al onze collega's voor je klaar om deze te beantwoorden.
Van: tom-englert <notifications@github.com>
Verzonden: Tuesday, 31 March 2020 13:09
Aan: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
CC: Johan Fontijne <johan.fontijne@twelve.eu>; Author <author@noreply.github.com>
Onderwerp: Re: [tom-englert/ResXResourceManager] Excel import problem (#308)


What has changed in the Excel file?

**Comment by tom-englert** [comment]
And the changes were not applied? If it's only a few, it might be overlooked - you could make a snapshot to see the changes.

**Comment by jfquarto** [comment]
No, there were quite a few changes actually. And I randomly checked some of them, they were not applied.
Also I see that the “File save” button stays disabled (most left icon in the menu); it should be enabled if changes were imported, right ?


​___
​
​Jouw twaalfde man,​
Johan Fontijne
Software developer
+31 182 700 500
Westbaan 200
​2841 MC Moordrecht
www.twelve.eu
​Wij heten vanaf nu Twelve!
​Na de overname van Quarto in 2018 zijn we nu officieel één bedrijf!
​Mocht je nog vragen hebben dan staan al onze collega's voor je klaar om deze te beantwoorden.
Van: tom-englert <notifications@github.com>
Verzonden: Tuesday, 31 March 2020 13:23
Aan: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
CC: Johan Fontijne <johan.fontijne@twelve.eu>; Author <author@noreply.github.com>
Onderwerp: Re: [tom-englert/ResXResourceManager] Excel import problem (#308)


And the changes were not applied? If it's only a few, it might be overlooked - you could make a snapshot to see the changes.

**Comment by jfquarto** [comment]
I did some further research.
I did another export, changed some texts myself in Excel and then imported that file. Works !
So I guess it must be in the xls file from the translator. Though it looks good, I will have a closer look at it.
Strange though that no error occurred, is there a silent logging or something ?




​___
​
​Jouw twaalfde man,​
Johan Fontijne
Software developer
+31 182 700 500
Westbaan 200
​2841 MC Moordrecht
www.twelve.eu
​Wij heten vanaf nu Twelve!
​Na de overname van Quarto in 2018 zijn we nu officieel één bedrijf!
​Mocht je nog vragen hebben dan staan al onze collega's voor je klaar om deze te beantwoorden.
Van: tom-englert <notifications@github.com>
Verzonden: Tuesday, 31 March 2020 13:23
Aan: tom-englert/ResXResourceManager <ResXResourceManager@noreply.github.com>
CC: Johan Fontijne <johan.fontijne@twelve.eu>; Author <author@noreply.github.com>
Onderwerp: Re: [tom-englert/ResXResourceManager] Excel import problem (#308)


And the changes were not applied? If it's only a few, it might be overlooked - you could make a snapshot to see the changes.

**Comment by tom-englert** [comment]
No, there is no silent logging. You can debug it to see where the problem is.
An please stop including the full history in every reply.

**Comment by tom-englert** [comment]
@jfquarto did you solve this?
