### ISSUE TITLE
Can't open the GUI after I close the VisualStudio2019

### ISSUE THREAD

**Issue by ZoolMons** [dotnet/ResXResourceManager#312]
I can only user once after I download in VisualStudio2019 Manage Extensions, after I close the VS, I can't open ResXManager by operaring clicking Tools => ResXManager. It'll show me nothing except the title. So I have to uninstall and download again, if i want to this plugin.
please forgive my poor English

**Comment by tom-englert** [comment]
These are problems related to the VSIX installer of Visual Studio.
Did you check out https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors

**Comment by tom-englert** [comment]
Closed as stale
