### ISSUE TITLE
Track updated labels and translation versioning workflow

### ISSUE THREAD

**Issue by MarcoIdWeb** [dotnet/ResXResourceManager#318]
It would useful a way for revision update changed labels.
I use comments as the versioning of each label using a revision number.
For example, if a developer changes a label, it increments the comment value by one.
When I translate, I will update others language and I will increment the number of the comment for each label of updated language.
If the numbers in the comments of a label are different in other languages, I need to translate and update. If all numbers are identical mean that no changes are made by developers or main language manager.

If developers add a label for the main language, it comments it as 0.

At the moment I do this workflow exporting in Excel. It would be useful an integrated comment compare tool, highlighting the inconsistent rows by this rule.

**Comment by tom-englert** [comment]
Maybe this is what you are looking for:
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Snapshots.md

**Comment by tom-englert** [comment]
@MarcoIdWeb ???

**Comment by MarcoIdWeb** [comment]
Thanks Tom. This is exactly what I need. I have to change my workflow but snapshots can solve my need. 
Thanks
