### ISSUE TITLE
Make ResXResourceManager as default editor

### ISSUE THREAD

**Issue by nithinbandaru1** [dotnet/ResXResourceManager#319]
Hi,

If possible it would be nice if ResXResourceManager is made the default editor for the Resx files.
So, on the double click, it will directly open ResXResourceManager instead of VisualStudio default editor.

Does Visual studio SDK have this feature? Hopefully, it has.

With regards,
Nithin B.

**Comment by tom-englert** [comment]
I don't think VisualStudio has this possibility.
Anyhow, the design of RXRM is that you never again need to open a specific .resx-file.
