### ISSUE TITLE
Make View in tab on file click and Popup View on Project or solution click

### ISSUE THREAD

**Issue by nithinbandaru1** [dotnet/ResXResourceManager#320]
Hi,

If possible it would be nice if ResXResourceManager is made to open in Tab instead of popup because it annoying in the popup because it feels like a great deviation from the workflow in Visual Studio.

All the coding is done in tabs and also default editor of Resx files open in a tab. So, it will be less distracting and easy handling of resource files. No need to open popup again and again.

Popup can be shown by providing a context menu option for a project or a solution or a folder.

With regards,
Nithin B.

**Comment by tom-englert** [comment]
Just drag it to the panel where you want it to dock, just like any other VisualStudio window.
