### ISSUE TITLE
Cannot connect to my cognitive service on Azure

### ISSUE THREAD

**Issue by seantsang-crypto** [dotnet/ResXResourceManager#321]
Hi,
Sorry for this dumb question.
I have created a translator resource on Azure.
However, I just can't connect it without inputting endpoint information in ResXResourceManager.
Anyone who can guide me how to use this feature?

Thanks!

**Comment by tom-englert** [comment]
Just enter one of your keys in the field named "Key:"

**Comment by seantsang-crypto** [comment]
Hi Tom,
Thanks for promptly reply.
I have tried that for so many times.
However, I think those 2 keys are for the endpoint URL.
I don't think we can just use any one of them on our ResX Resource Manager without supply endpoint URL.
thank you so much

**Comment by tom-englert** [comment]
The endpoint is always `https://api.cognitive.microsoft.com/` and is hard-coded.
What error message do you get from Azure Translator?

**Comment by seantsang-crypto** [comment]
Hi Tom,
I have recreated the service and moved the location from east Asia to global. Now it's working.
I am not sure if it was caused by the location.
I have checked the source code a little bit and was curious if it was the reason. Because the URL of the endpoint are different.
![trans](https://user-images.githubusercontent.com/65672954/82481021-42710180-9b07-11ea-9449-52439dfc3bca.png)

Anyway, it's working.

Thank you so much.

Regards,
Sean Tsang

**Comment by iravanchi** [comment]
I can confirm that I had the same issue when choosing "canadacentral" location. With the "global" location the problem went away.

@tom-englert  Maybe this is something that we can have in the Azure documentation wiki or as a hint in the plugin itself to avoid confusions.

**Comment by tom-englert** [comment]
@iravanchi what is the end point if it's not global? Maybe that really needs to be configurable.
The wiki is outdated, documentation has moved to the repo, so maybe s.o. can provide a PR with some hints?

**Comment by papuashu** [comment]
I have a similar issue: have a MS Tsanslator key, saved it to Resx Manager, but when it comes to translate something, Resx Manager shows an error ("Azure: Response status code does not indicate success: 401 (Access Denied)"). I think it's because it uses the URL displayed on top right: http://www.microsoft.com/en-us/translator/ ; I just assume that. Instead it should use this endpoint: https://api.cognitive.microsofttranslator.com/ (got it from my Azure Translator portal). Eventually this endpoint URL should be editable so that in case MS changes it one can re-configure this.

**Comment by tom-englert** [comment]
@papuashu it uses the correct endpoint (s. comments above). The linke on top-right is not the endpoint, it's the landing point for user documentation.

**Comment by papuashu** [comment]
@tom-englert thanks for the info; however the error is always there (401 Access Denied) although I have an API key and refreshed it in Resx Manager..
