### ISSUE TITLE
Update in Visual Studio 2019 Broken

### ISSUE THREAD

**Issue by galbamberg** [dotnet/ResXResourceManager#325]
Hello, I have an odd issue. I Updated the Resxmanager to Version 1.41. After the Update, it still says I have the version 1.40 installed (and no DEEPL Translation, so it seems I still have 1.40). If I try to update it again, it says: The current version is already installed for all products. 

Deinstalling and Reinstalling the extension did not fix the problem. 
Any suggestions?

**Comment by tom-englert** [comment]
Did you try everything listed here?
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md

**Comment by rwgtacos** [comment]
Same problem here. I am using VS 2017 Version 15.9.23. I removed resxmanager in Visual Studio and old versions of resxmanager with duplicateextensionfinder -delete. After that I removed an old resxmanager directory under C:\Users\rukon\AppData\Local\Microsoft\VisualStudio\14.0\Extensions. and installed resxmanager again. But after restart of Visual Studio 2017 it still says Version 1.40.344 was installed and an update is available.

The log-file of the VSIX-Installater contains:
08.06.2020 13:24:03 - Microsoft VSIX Installer
08.06.2020 13:24:03 - -------------------------------------------
08.06.2020 13:24:03 - vsixinstaller.exe version:
08.06.2020 13:24:03 - 16.6.2051
08.06.2020 13:24:03 - -------------------------------------------
08.06.2020 13:24:03 - Command line parameters:
08.06.2020 13:24:03 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:15.0.28307.1146,/appidname:Microsoft Visual Studio Professional 2017,/culture:de-DE,/noep,C:\Users\rukon\AppData\Local\Temp\VSIXezbbyiwo.vsix
08.06.2020 13:24:03 - -------------------------------------------
08.06.2020 13:24:03 - Microsoft VSIX Installer
08.06.2020 13:24:03 - -------------------------------------------
08.06.2020 13:24:05 - Initializing Install...
08.06.2020 13:24:05 - Erweiterungsdetails...
08.06.2020 13:24:05 - 	Identifier         : 43b35fe0-1f30-48de-887a-68256474202a
08.06.2020 13:24:05 - 	Name               : ResXManager
08.06.2020 13:24:05 - 	Author             : tom-englert.de
08.06.2020 13:24:05 - 	Version            : 1.40.3444
08.06.2020 13:24:05 - 	Description        : The most popular tool to localize and manage all kind of applications with resx-based resources. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.
08.06.2020 13:24:05 - 	Locale             : en-US
08.06.2020 13:24:05 - 	MoreInfoURL        : https://github.com/tom-englert/ResXResourceManager
08.06.2020 13:24:05 - 	InstalledByMSI     : False
08.06.2020 13:24:05 - 	SupportedFrameworkVersionRange : [4.6.2,)
08.06.2020 13:24:05 - 
08.06.2020 13:24:05 - 	SignatureState     : Unsigned
...

The installed file VSIXezbbyiwo.vsix has current date and time so I think the downloaded file is wrong.
Perhaps it helps if you upload the current version once again.

**Comment by galbamberg** [comment]
I completely uninstalled it. It was not in the extension list and tried to reinstall it.
On the machine of my colleague the same happened, but on his computer it was the first installation at all. So it is not the problem described in the link.

**Comment by tom-englert** [comment]
OK, uploaded the package again, can you retry?

**Comment by galbamberg** [comment]
Update now works. Version is 1.41 DeepL available.
Works for me

**Comment by rwgtacos** [comment]
For me it works now too.
Thank you.
