### ISSUE TITLE
Too Many Request

### ISSUE THREAD

**Issue by CSRodulfo** [dotnet/ResXResourceManager#330]
I receive the message MyMemoryÑ Response status code does indicate success 429 (Too Many Requests)

How can i do it?

**Comment by tom-englert** [comment]
Try to select less items to translate at once. 
Is there any documentation of the MyMemory API how many requests they support?

**Comment by tom-englert** [comment]
@CSRodulfo could you solve this?

**Comment by tom-englert** [comment]
Closed as stale
