### ISSUE TITLE
NeutralResourcesLanguage attribute not considered for neutral language

### ISSUE THREAD

**Issue by Thieum** [dotnet/ResXResourceManager#335]
I tested this behavior in a Class Library and a WinForms project, with .NET Framework. with a non-sdk csproj.

When I set the neutralResources Language Attribute in the project properties to a different language than english, it is not reflected in the ResX Resource Manager UI for the neutral column. It remains stuck to the english us flag : 

![image](https://user-images.githubusercontent.com/944894/87548210-2bb7d880-c67a-11ea-9129-91d84492ba3c.png)

**Comment by tom-englert** [comment]
You can change the neutral language in the configuration tab

**Comment by Thieum** [comment]
@tom-englert Ah I see, thanks a lot!
