### ISSUE TITLE
Does not match columns correctly

### ISSUE THREAD

**Issue by steam3d** [dotnet/ResXResourceManager#336]
I have project with two languages
1. ru-RU
2. en-US

I just open  ResXResourceManager and it shows en-US as Neutral language and my en-US empty now. When i try to add some value to en-US i get error.

It very strange behaviour. Why do ResXResourceManager create Neutral language if my project has default language en-US?
![image](https://user-images.githubusercontent.com/30986874/88515759-e047e780-cff4-11ea-93e6-4d7aadca6ff9.png)

**Comment by tom-englert** [comment]
There is always a neutral language, that's by desing of .resx resources
Just remove all files named `*.en-US.resx`

**Comment by steam3d** [comment]
I can't. I have only this files. 
If i delete the en-US my app lose en-US language 
![image](https://user-images.githubusercontent.com/30986874/88517921-47b36680-cff8-11ea-8492-10ad2c726397.png)

**Comment by tom-englert** [comment]
I see, you're using .resw, not .resx. Can you share the project where this happens (just without code source files)?

**Comment by steam3d** [comment]
Check this. 
[sample.zip](https://github.com/dotnet/ResXResourceManager/files/4980794/sample.zip)

**Comment by tom-englert** [comment]
I see, your mixing projects with .resx and .resw resources - that won't work, the concepts behind are too different.
.resx has an explicit neutral language, .resw not.

**Comment by tom-englert** [comment]
It woks if you remove the `*.en-us.resx` from the WPF project. They are not needed because you have en-US in the neutral language,
