### ISSUE TITLE
Any way to generate language JSON on save? (or by click of a button)

### ISSUE THREAD

**Issue by rolandtoth** [dotnet/ResXResourceManager#338]
I'm new to ResXResourceManager but so far so good. I started using it (as VS extension) and even with only 30 entries it spotted 4 issues with my 2-language setup, so it's really useful.

I tried to get info about generating JSON files automatically somehow but no success. My goal was to generate simple JSON files (flat key: value pairs) that would be used by Angular (they would be copied to the assets directory on Angular build).

I created an action method to retrieve JSONs in Angular, and while that works well, I'm curious whether the above feature can be accomplished somehow. This would allow Angular consume ready-made translation files without using backend resources.

**Comment by tom-englert** [comment]
https://github.com/tom-englert/L10N-Web-Demo

**Comment by rolandtoth** [comment]
That look nice, thanks. However in the current project there's ngx-translate/core and i18n, it would be hard to change. I'll try this next time when localization is needed.

**Comment by tom-englert** [comment]
@rolandtoth But the generated jsons work with ngx-translate, too, right?

**Comment by rolandtoth** [comment]
I guess so, the non-default JSON files look OK. Only that the translations are under the "Resources" so one should use Resources.key in the view files but that's no biggie.

**Comment by rolandtoth** [comment]
Hi again,

in new project I tried to follow the steps described in the readme above, but got stuck at this point:

> Now start Visual Studio or standalone ResXResourceManager and open your src/ folder. This will trigger the initial creation of the resources.ts file in the app/ folder next to your app.module.ts

What do you mean on opening the src/ folder? Expanding in the Solution Explorer? I tried that but no resources.ts was generated, not in the "app" folder (as per the .config file) but nowhere in the entire solution.

Using VS Enterprise 16.4.1
ResXManager 1.46.3794.0

It's a .NET Core 3.1 application with Angular 10. There's already a SharedResource.resx file, not sure if that matters. I tried to manually create the resources.ts file and see if it gets updated, but not. When saving the Resources.resx file, the language variant resx files are created next to it.

Any clues what to check?

**Comment by tom-englert** [comment]
> What do you mean on opening the src/ folder? 

`File > Open > Folder` in Visual Studio.
However if you have a solution that you open, the .config file must be next to the solution.

**Comment by rolandtoth** [comment]
Thanks, I was able to generate json files and resource.ts this way. However, putting the webexport.config file to the VS project root and modifying the paths I wasn't able to update those files again. We have the general .NET Core SPA project setup, so the Angular app goes to the ClientApp subfolder of the project. So opening another VS instance for managing translations doesn't seem to fit in the project workflow. 

Perhaps I am missing somethig but after all I think I'll opt out from the l10n setup. ResXResourceManager still remains the tool to use for the resx files for the i18n stuff. Thanks for the help!

**Comment by tom-englert** [comment]
I'm not should what you are struggling with - ResXManager does not make any assumptions about your project structure. It reads the config file from the solution folder, and if it exists, it creates the files at the locations specified.

> However, putting the webexport.config file to the VS project root...

What do you mean by "VS project root"? Is this the solution`s folder?

**Comment by rolandtoth** [comment]
Yes, the project root - I should have tried putting in the solutions's root since that's what we open. Should the "l10n" folder be in the same directory as the config file? And does code generation work in "Solution view" or only in "Folder view" in VS (Solution Explorer)?

**Comment by tom-englert** [comment]
Works in both solution or folder view
The output folders can be everywhere, just depends on your project structure..
