### ISSUE TITLE
Blazor(Server) - working RegEx pattern

### ISSUE THREAD

**Issue by Foizman** [dotnet/ResXResourceManager#339]
**Hi there,**

in Server-side Blazor (C#) we use something like this

![image](https://user-images.githubusercontent.com/60654005/89706412-addbaa00-d965-11ea-8a5b-cdeaee6b9a49.png)

![image](https://user-images.githubusercontent.com/60654005/89706408-9ef4f780-d965-11ea-8e8e-5342d08ab0c0.png)

The file-extension for Blazor-files is: **.razor**

I couldn't find any working variation of a regular expression, which hits any keyword, always counts 0

![image](https://user-images.githubusercontent.com/60654005/89705527-60a80a00-d95e-11ea-8e85-79c835a1a189.png)

Any ideas?

Cheers,
Volker

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/89708655-2e57d600-d979-11ea-86f4-e2dd7b536b3a.png)
```html
test.razor:
<div>
  <b>@LangBasic["Note"]:</b>
  <b>@LangBasic["Test1"]:</b>
  <b>@LangBasic["Test2"]:</b>
  <b>@LangBasic["Test1"]:</b>
</div>
```
![image](https://user-images.githubusercontent.com/10229954/89708627-ffd9fb00-d978-11ea-8a58-612263552f85.png)

Just tried and it works fine...

**Comment by Foizman** [comment]
Thank you, I removed the entry, retyped it using a very simplyfied version \["($Key)"\] and now it works.
Absolutely no idea, anyway... done!

Cheers from Graz/Austria!
