### ISSUE TITLE
Please add selection of indentation char

### ISSUE THREAD

**Issue by DanAvni** [dotnet/ResXResourceManager#342]
My resource files are indented with tab character and not spaces. Please add an option to select the indentation character (basically it should be like below - taken from some other project I have)
`XmlWriterSettings xws = new XmlWriterSettings() { Indent = true, IndentChars = "\t", Encoding = utf8EncoderNoBOM };`

**Comment by tom-englert** [comment]
Maybe related to #233.
If someone picks up this one, maybe both issues sholuld be addressed.

**Comment by tom-englert** [comment]
Closing this as stale. Anyhow this is not configurable in the internal editor, and RXRM should not behave different.
