### ISSUE TITLE
Can't update to v1.43

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/ResXResourceManager#344]
When trying to update, the VSIX installer displays the following message:
```
This extension is already installed to all applicable products.
```

When looking inside the .vsix file, I see that the version in extension.vsixmanifest is still `1.42.3648`.
The version in src/ResXManager.VSIX/source.extension.vsixmanifest was changed to 1.43 in commit 6bd580430bb199051ed5df3ad3baf5c7516749f5, but somehow this was not reflected in the final file?

**Comment by JeroenOortwijn** [comment]
The ResXManager.VSIX.dll is also version 1.42.3648, so it looks like the whole .vsix file is still the old version instead of version 1.43.3735.

**Comment by tom-englert** [comment]
Uploaded again...
