### ISSUE TITLE
2020-08-27 Include empty rows in cell height calculations i Group View

### ISSUE THREAD

**Issue by clfey** [dotnet/ResXResourceManager#346]
Version = ??

1,2: Insert paragraph separators (ENTER)
3: Click to the left of the blue-marked row to re-scale the cell height
4: The cell height may have been calculated disregarding the empty rows, i.e. the cell height is not sufficient to show the text.

- [ ] Please include empty lines in the calculation of cell height.

![image](https://user-images.githubusercontent.com/8375198/91424501-28f3fa00-e85a-11ea-9519-d7b6af571db6.png)

**Comment by tom-englert** [comment]
That's intended. The row height is simply limited, else the table would get unusable when containing several large text fragments.
To edit large texts, use the editor at the top.

**Comment by clfey** [comment]
OK, makes sense.
