### ISSUE TITLE
2020-08-27 Auto-focus on Last Marked Row when crossing out the search pattern

### ISSUE THREAD

**Issue by clfey** [dotnet/ResXResourceManager#348]
Version = ??

1: I enter a search text, here in French "Une ligne courbe".
2: The output window (the small window at the bottom) shows the Key and the ResX filename.
3: In parenthesis it shows the path to the ResX file's folder.
4: I click somewhere in my current row to re-size and to mark it (blue)
5: The ResX file spec is NOT highlighted in the browser section to the left
6: I cross out the search text. All resX rows are now shown, I don't see "my row" anymore. It is blue, but lost between thousands of other texts. I do not want to scroll a lot to try to find it, but I would like to have it in focus.
7: The file name and folder name are still shown at the bottom
8: But the file spec is still not shown to the left.
9:
- [ ]  Please highlight the currently marked row in the browser section to the left.
- [ ] Please let the marked row (the last one edited) be in focus in the main group view window when the search pattern has been crossed out.
- [ ] Please add the ResX file name after the ResX folder path at the bottom, this makes it easier to copy-paste to Windows for opening of the file

- [ ] Please add that a double-click-action in the bottom window on the file name triggers opening of the file with currently associated XML text editor. In my case, I like to associate ResX files with Notepad++.

![image](https://user-images.githubusercontent.com/8375198/91426093-5346b700-e85c-11ea-9722-ce9121f4bbf1.png)

**Comment by tom-englert** [comment]
- The intention of this tool is to provide an abstraction layer that hides the details of files from the user, so he can concentrate on localizing.
- The display in the status bar (7 and 3) is NOT a single file name - it refers to ALL language files defining this resource. In your sample the content of the selected resource is spread across 3 files, so which one would you open on double click?
- To get an overview of where your resource is located, use the grouped view, not the flat view. A double click on the group header will then select the entity in the left panel (5)
- Consider exporting to Excel if you need more editing features

**Comment by clfey** [comment]
I find the ResX Manager software to be a great tool, and I would really love to see it expand its user base.

The explanation provided anove is good, but it needs to be included as info where me and new RXRM users would find it.

As a product owner (other github project) and beginner with RXRM, and not being a C# programmer myself, I would still suggest to provide more info in tooptips & help such that people like me would find the info when needed. Explaining concepts in this github issue won't help those who follow as RXRM stand-alone users.

**Comment by tom-englert** [comment]
It's open source, and even non-programmers can contribute by e.g. improving the documentation: https://github.com/dotnet/ResXResourceManager/tree/master/Documentation
