### ISSUE TITLE
FileNotFoundException after delete resx file!

### ISSUE THREAD

**Issue by huangjinshe** [dotnet/ResXResourceManager#351]
I output my rest to Excel, and then add new language add a new language from Excel.
But if I delete the resx file manually by Visual studio 2019(which file I import from Excel), then the Visual Studio will always display error: 

```
错误： System.IO.FileNotFoundException: 未能找到文件“Y:\test\MyproJect\Resource.en-US.zh-CN.resx”。
文件名:“Y:\test\MyproJect\Resource.en-US.zh-CN.resx”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   在 System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   在 System.Xml.XmlTextReaderImpl.FinishInitUriString()
   在 System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   在 System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   在 System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   在 System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   在 ResXManager.Model.ProjectFile.InternalLoad()
   在 ResXManager.Model.ProjectFile.Load()
   在 ResXManager.Model.ResourceLanguage..ctor(ResourceEntity container, CultureKey cultureKey, ProjectFile file, DuplicateKeyHandling duplicateKeyHandling)
   在 ResXManager.Model.ResourceEntity.<>c__DisplayClass44_0.<GetResourceLanguages>b__2(<>f__AnonymousType1`2 <>h__TransparentIdentifier0)
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   在 ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, DuplicateKeyHandling duplicateKeyHandling)
   在 ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, DuplicateKeyHandling duplicateKeyHandling)
   在 ResXManager.Model.ResourceManager.<>c__DisplayClass52_0.<LoadEntitiesAsync>g__Load|2()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__52.MoveNext()

```

I thought although I delete the file, but there is still some link in .csproj file, But I didn't find that. How should I do?

**Comment by tom-englert** [comment]
If the refresh button does not work, just reload the project or solution.

**Comment by huangjinshe** [comment]
@tom-englert , I did not use refresh button, but I try to restart the solution. But not working.

**Comment by tom-englert** [comment]
I can't reproduce such a behavior. Can you post a sample project and a more detailed description how to reproduce it?

**Comment by huangjinshe** [comment]
Here is a Video Record for let you know the problem: https://file.io/AROhiaCV3OcW

Download sample project for test: [Oybab Trading System](https://github.com/oybab/TradingSystem)

Basically I try to add a new resx file:`en-IE`, and I found the resx file name not correct after import from Excel, then I deleted the resx file, after that my project just keep telling me: file missing.

**Comment by tom-englert** [comment]
Sorry, that link to file.io says "404 Page not found"

**Comment by huangjinshe** [comment]
@tom-englert , Because github file limit, I can only upload it to some server as a temporary file.
This is the new link: https://a.uguu.se/vpcqmo.avi
It will expire after 24 hours, download it ASAP.

**Comment by tom-englert** [comment]
Your problem is that you have linked the same resource files into three projects. If you delete the source file, you have to delete the links in the other projects, too.
![image](https://user-images.githubusercontent.com/10229954/91641170-f1847980-ea22-11ea-8c99-7d767d7c65e6.png)

**Comment by tom-englert** [comment]
BTW, you don't have a neutral resource language - and bypass all the cool features about using resources like static typed access.
Instead you use a very error prone way to access the resources, using magic keys spread over the whole app. Is this intended?

**Comment by tom-englert** [comment]
PS. If you add a new language column in ResXManager instead of Excel, you can't mistype it.

**Comment by huangjinshe** [comment]
@tom-englert , Ok now I understand that. I didn't notice that this software so much intelligent, even could auto add the link to other place.

Yes, I don't need to use static typed access way to access the resources.

But my last question is: why the language which I import from excel generate as: `Resources.en-Us.en-IE.resx`? but It should be: `Resources.en-IE.resx`.

**Comment by tom-englert** [comment]
It's because there is no neutral file.

**Comment by huangjinshe** [comment]
@tom-englert , Thanks for let me know. I will rename it by myself.
