### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by LUISCARLOSH** [dotnet/ResXResourceManager#353]
When I try to Install it I receive this message>
**VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products**
Mi Visual Studio Version Installed is:

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Net Framework 4.7.03190

Please help!

**Comment by tom-englert** [comment]
VS 2015 is no longer supported. Either upgrade VS, or use the standalone version, as described in the readme.

**Comment by LUISCARLOSH** [comment]
I have installed using ClickOnce and I can open de software now…

But I don have clear how use ir with my two resx files  es.resx (spanish) and en.resx(english)

How integer the application with VS In order to manage the resx

Luis
Mexico

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: tom-englert<mailto:notifications@github.com>
Enviado: sábado, 29 de agosto de 2020 08:37 a. m.
Para: dotnet/ResXResourceManager<mailto:ResXResourceManager@noreply.github.com>
CC: LUISCARLOSH<mailto:luis_carlosh@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [dotnet/ResXResourceManager] This extension is not installable on any currently installed products. (#353)


VS 2015 is no longer supported. Either upgrade VS, or use the standalone version, as described in the readme.

**Comment by tom-englert** [comment]
Did you read the documentation?
