### ISSUE TITLE
Crash  of devenv.exe when opening ResX window

### ISSUE THREAD

**Issue by edika99** [dotnet/ResXResourceManager#354]
It is a week that I've started experiencing some problem when opening ResX.
Visual Studio crash asking to debug devenv.exe and then close.
Trying to debug the expetion is the following

System.InvalidOperationException: 'Sorting' is not allowed during an AddNew or EditItem transaction.

I don't know which module cause the crash but this happen only when I open ResX .

Im using
Microsoft Visual Studio Community 2019 (2)
Versione 16.6.3

**Comment by tom-englert** [comment]
Can you add the stack trace of the exception, please?

**Comment by edika99** [comment]
When opening Visual Studio to debug the crash it show me only this exception  because the source is not available.

This is what I found in the windows registry:

**Comment by edika99** [comment]
I've notice that usually it happen when switching from another tab to ResX's tab.

**Comment by tom-englert** [comment]
OK, with the stack trace it's clear what happens. 
What operation system are you running?
