### ISSUE TITLE
Too many languages, list does not scroll

### ISSUE THREAD

**Issue by jerry1970** [dotnet/ResXResourceManager#357]
When there are too many languages to fit on the screen, it's impossible to select languages because the dropdown does not scroll.

![image](https://user-images.githubusercontent.com/5627407/92565212-94869000-f27a-11ea-966f-394d663b2804.png)

Is there another way to select the languages I want to see?

**Comment by tom-englert** [comment]
Currently not. 
Which project is this? Looks like a good canditate for testing.

**Comment by tom-englert** [comment]
@jerry1970 Which project is this? Looks like a good canditate for testing.

**Comment by jerry1970** [comment]
@tom-englert this is from the product the company I work for develops, cannot share anything from that.
But I guess I could create any empty project and add 50 languages with just one key or something to test this.

**Comment by tom-englert** [comment]
@jerry1970 If that's a commercial product, this would be a good feature to contribute...

**Comment by jerry1970** [comment]
@tom-englert, it is, and I realise that, but the translators use their own software, it's only for the developers, and now JetBrains have introduced their Localisation Tool I doubt they want us to spend time on that.
