### ISSUE TITLE
Crash on Visual Studio Professional 2019

### ISSUE THREAD

**Issue by LightAndrek** [dotnet/ResXResourceManager#358]
After updating the ResxResourceManager to version 1.45.3764, I'm no longer able to open the extension. I tried to uninstall the extension and reinstall it after cleaning the files left by visual studio but the problem persists. The strange thing is that the extension works on first launch, but after closing visual studio I am no longer able to open it.

This is the _ActivityLog.xml_ content:

	CreateInstance failed for package [VsPackage]Source: "mscorlib" Description: Eccezione generata dalla destinazione di una chiamata.
	System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. > System.IO.FileNotFoundException: Non è stato possibile caricare il file o l'assembly "TomsToolbox.Composition, Version=2.1.1.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2" o una delle relative dipendenze. Impossibile trovare il file specificato.
	in ResXManager.VSIX.VsPackage..ctor()
	--- Fine della traccia dello stack dell'eccezione interna ---
		in System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
		in System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
		in System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
		in System.Activator.CreateInstance(Type type, Boolean nonPublic)
		in System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
		in System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
		in System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
		in System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Non è stato possibile caricare il file o l'assembly "TomsToolbox.Composition, Version=2.1.1.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2" o una delle relative dipendenze. Impossibile trovare il file specificato.
		Nome file: "TomsToolbox.Composition, Version=2.1.1.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2"
		in ResXManager.VSIX.VsPackage..ctor()

		AVV: la registrazione dell'associazione di assembly è disattivata.
		Per abilitare la registrazione degli errori di associazione di assembly, impostare il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) su 1.
		Nota: alcune penalità di prestazione sono associate alla registrazione degli errori di associazione di assembly.
		Per disattivare la funzionalità, rimuovere il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog].

This is my Visual Studio Installation infos:

> Microsoft Visual Studio Professional 2019
Versione 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Versione 4.8.04084
Edizione installata: Professional
Visual C++ 2019   00435-20310-66664-AA799
Microsoft Visual C++ 2019
.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.
Add New File   3.5.138
The fastest and easiest way to add new files to any project - including files that start with a dot
ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools
ASA Service Provider   1.0
ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019
ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.
ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
Per altre informazioni, vedere https://www.asp.net/
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.6.1000.1
Microsoft Azure Data Lake Tools for Visual Studio
Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools
Azure Stream Analytics Tools for Visual Studio   2.6.1000.1
Microsoft Azure Stream Analytics Tools for Visual Studio
Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.
Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.
CodeMaid   11.1.209
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
Crystal Reports per .NET Framework   
Crystal Reports per .NET Framework
CSS Tools 2019   1.1.4
Provides additional features to the CSS editor in Visual Studio.
Dotfuscator Community Edition   5.44.0.10087-6530a8d80a
PreEmptive Protection - Dotfuscator CE
EditorConfig Language Service   1.17.284
Language service for .editorconfig files.
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio
Estensioni per Strumenti contenitore di Visual Studio (anteprima)   1.0
Consente di visualizzare, gestire ed eseguire la diagnosi dei contenitori all'interno di Visual Studio.
Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
Fabric.DiagnosticEvents   1.0
Eventi di diagnostica di Fabric
File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer
File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually
Gestione pacchetti NuGet   5.7.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/
GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.
Image Optimizer   4.0.132
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.
Image Sprites   1.4.61
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.
Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.
Microsoft Azure HDInsight Azure Node   2.6.1000.1
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.6.1000.1
Language service for Hive query
Microsoft Azure Stream Analytics Language Service   2.6.1000.1
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.
Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.
Office Developer Tools per Visual Studio   16.0.30215.00
Microsoft Office Developer Tools per Visual Studio
Open Command Line   2.4.229
2.4.229
Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC
Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio
Package Installer   2.0.103
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project
Package Security Alerts   1.0.22
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.
Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
ResXManager   1.45.3764.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.
SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.
SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools
SQL Server Reporting Services   15.0.19124.0
Finestre di progettazione Microsoft SQL Server Reporting Services
Versione 15.0.19124.0
SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.
Strumenti C#   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.
Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.
Strumenti del Servizio app di Azure versione 3.0.0   16.7.532.28833
Strumenti del Servizio app di Azure versione 3.0.0
Strumenti di Microsoft Azure   2.9
Strumenti di Microsoft Azure per Microsoft Visual Studio 2019 - versione 2.9.30701.1
Strumenti di Microsoft Azure Service Fabric per Visual Studio   16.0
Strumenti di Microsoft Azure Service Fabric per Visual Studio
Strumenti di recapito continuo Microsoft per Visual Studio   0.4
Consente di semplificare la configurazione delle pipeline Azure DevOps direttamente dall'IDE di Visual Studio.
Strumenti di Visual Basic   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.
Strumenti di Workflow Manager 1.0   1.0
Questo pacchetto contiene i componenti di integrazione di Visual Studio per il servizio Workflow Manager.
Strumenti TypeScript   16.0.20702.2001
Strumenti TypeScript per Microsoft Visual Studio
SVG Viewer   1.0.9
Makes it much easier to work with SVG files by showing a live preview in the bottom-right corner of the code window
Syntax Highlighting Pack   2.8.134
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...
Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.
Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
Test Adapter for Google Test   1.0
Consente di usare gli strumenti di test di Visual Studio con unit test scritti per Google Test. Le condizioni d'uso e le comunicazioni relative a terze parti sono disponibili nella directory di installazione dell'estensione.
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
Visual F# Tools 10.10.0.0 per F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 per F# 4.7
Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake
Visual Studio Tools per contenitori   1.0
Visual Studio Tools per contenitori
Visual Studio Tools per Kubernetes   1.0
Visual Studio Tools per Kubernetes
Visual Studio Tools per Unity   4.7.1.0
Visual Studio Tools per Unity
VisualStudio.DeviceLog   1.0
Informazioni sul pacchetto
VisualStudio.Mac   1.0
Mac Extension for Visual Studio
Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files
Web Essentials 2019   0.5.10
The easiest way to set up Visual Studio for the ultimate web development experience.
Xamarin   16.7.000.440 (d16-7@358f3c6)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.
Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Estensione di Visual Studio per abilitare gli strumenti di Xamarin Designer in Visual Studio.
Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f
Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
ZenCoding   1.2.12
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by tom-englert** [comment]
This is not an issue with ResXResourceManager, but with VisualStudio/VSIXInstaller. 
The only thing you can do is to 
- uninstall the extension, 
- restart VS
- verify extension is really uninstalled
- restart VS again
- re-install the extension

If this does not help, report the problem to Microsoft...

**Comment by tom-englert** [comment]
Updated [Troubleshooting.md](https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md)
