### ISSUE TITLE
Azure : Response status code does not indicate success 401

### ISSUE THREAD

**Issue by calebmakore** [dotnet/ResXResourceManager#360]
Hi, After adding Key for Azure translator I get the following error:  Response status code does not indicate success 401.  The key is correct and I am not sure why I am getting access denied.  I tried both stand-alone and Visual studio plugin.  Thank you for your help.

**Comment by tom-englert** [comment]
Maybe that's related to #321? What is your endpoint?

**Comment by tom-englert** [comment]
Closed as stale
