### ISSUE TITLE
Fix for issue #356 is causing a large performance penalty on loading large resx files

### ISSUE THREAD

**Issue by peterdingjensen** [dotnet/ResXResourceManager#363]
Setup: 
- Directory with a single resx file containing 52k keys in neutral language plus 2 other languages.
- All consistency checks disabled.
- Flat view mode.

Performance output of opening the application (and loading files) with the application compiled from commit be47eee1 (Fix #356):
14:09	Started
14:09	ResX Resource Manager loaded.
14:09	Assembly location: C:\Repos\ResXResourceManager\src\ResXManager\bin\Release
14:09	Version: 1.45.0.0
14:09	>>> 1: ResourceManager.Load @14:09:01.1
14:09	>>> 2: Enumerate source files @14:09:01.1
14:09	<<< 2: Enumerate source files 00:00:00.0284759
14:09	>>> 3: ListBox.SelectAll @14:09:01.7
14:09	<<< 3: ListBox.SelectAll 00:00:00.0329715
14:09	>>> 4: ListBox.SelectAll @14:09:04.9
14:12	<<< 1: ResourceManager.Load 00:03:38.2147897
14:12	<<< 4: ListBox.SelectAll 00:03:34.9966661
14:16	>>> 5: ListBox.SelectAll @14:16:54.5
14:16	<<< 5: ListBox.SelectAll 00:00:00.0345233

Performance output from same behaviour, but code compiled from commit d5f27f49 (Fix #355)
14:28	Started
14:28	ResX Resource Manager loaded.
14:28	Assembly location: C:\Repos\ResXResourceManager\src\ResXManager\bin\Release
14:28	Version: 1.45.0.0
14:28	>>> 1: ResourceManager.Load @14:28:43.6
14:28	>>> 2: Enumerate source files @14:28:43.6
14:28	<<< 2: Enumerate source files 00:00:00.0310656
14:28	>>> 3: ListBox.SelectAll @14:28:44.2
14:28	<<< 3: ListBox.SelectAll 00:00:00.0315200
14:28	>>> 4: ListBox.SelectAll @14:28:47.3
14:28	<<< 1: ResourceManager.Load 00:00:06.0231186
14:28	<<< 4: ListBox.SelectAll 00:00:03.3906532
14:28	>>> 5: ListBox.SelectAll @14:28:58.4
14:28	<<< 5: ListBox.SelectAll 00:00:00.0217143**To Reproduce**

So it seems the loading goes from something measured in few seconds to minutes.

As far as I can tell, it is related to the change in data source for "GroupedResourceTableEntriesSource" in ResourceView.xaml. I tried profiling both scenarios, but as I have no WPF experience I had to give up on finding the exact cause.

Before the fix for #356 :
![profile-before-356](https://user-images.githubusercontent.com/72496176/95333677-5eeeba00-08ad-11eb-986a-8d8c0bb7577d.png)

And after the fix:
![profile-after-356](https://user-images.githubusercontent.com/72496176/95333697-64e49b00-08ad-11eb-9675-e57b9bd81a9b.png)

Note: The run for the after/slow case was not completed as it was very slow due to the type of profiling.

**Comment by tom-englert** [comment]
I can't reproduce this. My test set is 20K entries in multiple resx files, and there is no difference between the two versions...
Can you share your data?

**Comment by peterdingjensen** [comment]
I can't share the exact data, but I've generated a data set giving similar performance:
[test_52k.zip](https://github.com/dotnet/ResXResourceManager/files/5348137/test_52k.zip)

I tried with 20k keys as well, and in this case it is significantly faster (0:36m vs 4:30m), but still quite slower than before.
