### ISSUE TITLE
Applying Translations do not create new resources to target language files.

### ISSUE THREAD

**Issue by rkarina94** [dotnet/ResXResourceManager#364]
Steps:
1. I have attempted a quick translation using MS Terminology which has provided a few translations. 
2. I clicked on Apply All and the records with translations disappear from the list. 
3. Checking TFS versions, no changes were done to the target Resource language file. 
4. When I come back to the Translation tab, the records reappear and the target language resource file does not get updated with the new resources.

Have attached images for the steps.

Expected Outcome: 
Once I click apply all/apply selected, new resources with the translated words should be added to the target language resource files.

![image](https://user-images.githubusercontent.com/28332589/95401042-f1e42e80-0957-11eb-8291-974fa78b2c07.png)
![image](https://user-images.githubusercontent.com/28332589/95401210-5dc69700-0958-11eb-8600-50f581c5b473.png)
![image](https://user-images.githubusercontent.com/28332589/95401280-8e0e3580-0958-11eb-90a4-fc60d50f9551.png)
![image](https://user-images.githubusercontent.com/28332589/95401390-cc0b5980-0958-11eb-827e-f1aaa2534daf.png)

**Comment by tom-englert** [comment]
Can't reproduce this. 
- Is there any message in the output panel?
- Since you are talking about TFS - maybe you have to checkout the files first?

**Comment by tom-englert** [comment]
Seems this is a timing issue with the change events from Visual Studio when applying translations where the resource file does not exist yet.

**Comment by rkarina94** [comment]
By timing issue you mean the changes are still occurring in the background, even though the UI shows us the translations have been applied? The Resource files are already checked out, when changes are made manually, they're checked out automatically.

**Comment by tom-englert** [comment]
An item-change event of VS sometimes has triggered a reload from disk before the changes had been saved.
