### ISSUE TITLE
I'm unable to re-enable ResxManager

### ISSUE THREAD

**Issue by FrancescoGiossi** [dotnet/ResXResourceManager#365]
I use ResxManager since the very beginning on the project, but now I'm stuck in a limbo.

Visual studio 2015

1. I disabled all the extensions
2. I did what I needed to do
3. Went back to the extensions form, I could see all the extensions as [disabled], but ResxManager
4. I could not find another way to restore it back
5. So I downloaded the latest version and tryed to install it. No joy, It says the version is already installed for all the available products
6. I tried to manually unistall ResxManager, from a developer command prompt, using the /u:43b35fe0-1f30-48de-887a-68256474202a switch, no joy

So far, I have no idea what I can do more to have ResxManager back in vs2015
Any idea?
![Untitled](https://user-images.githubusercontent.com/37366914/95732504-1f471a00-0c81-11eb-87b2-e50d95f010f6.png)

**Comment by tom-englert** [comment]
Sorry, the latest version does no longer support VS2015. You can use the standalone version instead.
