### ISSUE TITLE
Can you add zh-HK?

### ISSUE THREAD

**Issue by yzb110** [dotnet/ResXResourceManager#366]
There is zh-HK (Hong Kong Traditional Chinese) in Windows 10 regional settings, but zh-HK not in the drop-down option of resxresourcemanager,
Where does this option come from? Can you add it?

**Comment by tom-englert** [comment]
the possible languages are all languages that DotNet supports (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultures)

Maybe an update of your dotnet framework helps?

**Comment by tom-englert** [comment]
I'm using .NET Framework 4.8:
![image](https://user-images.githubusercontent.com/10229954/96247864-f7222880-0faa-11eb-8ef3-af7313f52d5d.png)
