### ISSUE TITLE
Some of the resx do not show at the rex panel

### ISSUE THREAD

**Issue by albertmata** [dotnet/ResXResourceManager#371]
Hi, I have a very large project with a lot of forms and resx files.
When I open the tool I see only a few of my files. In the alphabetical list of resources they are all listed to a certain extent that they do not appear anymore, the resource files that are not listed do not have the context menu option to "Open in Resx Manager" either

I have tried to open and close visual studio, recompile the whole project, etc... but I still can't see or open some of these files in the tool.

I'm using Vs 2015 Update 3 and the latest version of the tool.

**Comment by tom-englert** [comment]
Hard to say what goes wrong with this vague description.
Btw VS2015 support has been dropped some time ago

**Comment by albertmata** [comment]
I've opened my project with Vs2019 and then it showed this error:

[image: image.png]

In Vs2019 after this error is shown I cannot open any file on the
resxresourcemanager.
In Vs2015 I cannot open any file after this one ( alphabetically )

However this file is a valid xml file, I attach the file for inspection.
Thanks for your help, please let me know if I can help or provide more
information.


Missatge de tom-englert <notifications@github.com> del dia dj., 19 de nov.
2020 a les 13:33:

**Comment by tom-englert** [comment]
Is there anything helpful in the output panel?

**Comment by tom-englert** [comment]
There is no image and no file attached, can you try again?

**Comment by albertmata** [comment]
Sorry, I replied by mail and the attachments are gone.

Here is the error:
![image](https://user-images.githubusercontent.com/440629/99695449-df4c3180-2a8d-11eb-814f-f7d70aa7cdb4.png)

And the file:
[FichaConfiguracionPasarelaFAX.Strings.ca.zip](https://github.com/dotnet/ResXResourceManager/files/5568321/FichaConfiguracionPasarelaFAX.Strings.ca.zip)

The output panel:
ResX Resource Manager loaded.
Home: https://github.com/dotnet/ResXResourceManager
Report issues: https://github.com/dotnet/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: c:\users\albert\appdata\local\microsoft\visualstudio\16.0_6701bbed\extensions\z0zmkdol.csl
Version: 1.48.3862.0
.NET Framework Version: 528372 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=False (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)
Error: System.InvalidOperationException: C:\Proyectos Pragma\ADMINET\Principal\Clientes\Comun\General\ConfiguracionServidor\FichaConfiguracionPasarelaFAX.ca.resx is not a valid RESX resource file: No xml root. ---> System.Xml.XmlException: '.', valor hexadecimal 0x00, es un carácter no válido. línea 219, posición 8.
   en System.Xml.XmlTextReaderImpl.Throw(Exception e)
   en System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   en System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   en System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   en System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   en System.Xml.XmlTextReaderImpl.Read()
   en System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   en System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   en System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   en System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   en ResXManager.Model.ProjectFile.Load()
   en ResXManager.Model.ResourceLanguage..ctor(ResourceEntity container, CultureKey cultureKey, ProjectFile file, DuplicateKeyHandling duplicateKeyHandling)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en ResXManager.Model.ResourceLanguage..ctor(ResourceEntity container, CultureKey cultureKey, ProjectFile file, DuplicateKeyHandling duplicateKeyHandling)
   en ResXManager.Model.ResourceEntity.<>c__DisplayClass46_0.<GetResourceLanguages>b__2(<>f__AnonymousType1`2 <>h__TransparentIdentifier0)
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   en ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, CultureInfo neutralResourcesLanguage, DuplicateKeyHandling duplicateKeyHandling)
   en ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, CultureInfo neutralResourcesLanguage, DuplicateKeyHandling duplicateKeyHandling)
   en ResXManager.Model.ResourceManager.<>c__DisplayClass52_0.<LoadEntitiesAsync>g__Load|2()
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__52.MoveNext()

**Comment by tom-englert** [comment]
Looks obvious, just fix the file

**Comment by albertmata** [comment]
Ok, now I see the file has some weird characters at the end.
Thanks for your time.

Missatge de tom-englert <notifications@github.com> del dia dj., 19 de nov.
2020 a les 21:38:
