### ISSUE TITLE
Detect Code References in Xaml file for Xamarin.Forms when using IMarkupExtension

### ISSUE THREAD

**Issue by EmilAlipiev** [dotnet/ResXResourceManager#373]
I have just went through documentation and several similar issues here but I cant figure out why Detect Code References not finding any Xaml reference in my xamarin.forms project. Here how it looks like the reference in my xaml

`  <Label Text="{resx:Translate Details}" />`

So basically no file name but only Key as Details, I have tried followings with .xaml file extension
![image](https://user-images.githubusercontent.com/10422347/101964179-cfe58180-3c10-11eb-9dfb-1feabb81567e.png)

`\W($Key)\W`

I thought this should search all xaml files as Key

I have tried also simple `\($Key)`  but also not working.

Can you advise something? Ideally would be nice to search with a prefix like `^Translate\W($Key)\W` not sure if that will work.
But i think that most of the Xamarin users can benefit from that because mostly we use IMarkupExtensions with Xaml usage like above.

**Comment by tom-englert** [comment]
I can't see what should be wrong here. Can you post a screen shot of your resources, too?

**Comment by tom-englert** [comment]
- Sometimes you may have to restart VS until the changes will be active
- `\($Key)` is definitely wrong, escaping the first bracket will render the regular expression invalid.

**Comment by EmilAlipiev** [comment]
strange yesterday wasn't working and today it works with `\W($Key)\W ` probably like you said a restart was needed. Danke :)
