### ISSUE TITLE
Custom dialect resource files not loaded and shown as expected

### ISSUE THREAD

**Issue by Ronzan** [dotnet/ResXResourceManager#376]
Not sure if this is a bug or by design.
My issue is that we have custom dialects in our project.
That is, we have .resx files with custom language codes like: en-GB-dev or en-GB-x-abc.
These custom dialect files are seen as separate resources and not as different languages.

ResXResourceManager:
![image](https://user-images.githubusercontent.com/4838857/103893051-80498700-50e4-11eb-9634-11fa9cd871de.png)

This is apparently also an issue for VS, this is the folder in the project:
![image](https://user-images.githubusercontent.com/4838857/103893123-a707bd80-50e4-11eb-900b-ebb0291709f7.png)

**To Reproduce**
Add two resource files with standard dialects, en-GB and en-US
Add a resource file with a custom dialects, en-GB-dev
Open ResXResourceManager and observe.

**Expected behavior**
I expected ResXResourceManager to show custom dialects the same way it shows standard dialects.

Is this an issue with ResXResourceManager, .NET, VS or what? :-)

**Comment by tom-englert** [comment]
Currently RXRM considers only languages known by Windows (anything returned by `CultureInfo.GetCultures(CultureTypes.AllCultures)`):
https://github.com/dotnet/ResXResourceManager/blob/96ec5cc840b0c12ed66431f78147919ff3f22639/src/ResXManager.Model/ResourceManager.cs#L269-L292

Maybe you have a better approach?

**Comment by Ronzan** [comment]
I haven't looked over the source much yet, and I haven't found where the resx files are actually loaded.
I think the .GetCultures() makes good sense for the list of languages, I don't see a better option for that.
I'll see if I can find where RXRM is deciding what files to load :)

**Comment by tom-englert** [comment]
Actually the files will be loaded. However since  `en-GB-dev` is not detected as a valid language name, it is treated as the neutral culture of the `SharedResource.en-GB-dev`, not as a specific culture of `SharedResource`

**Comment by Ronzan** [comment]
Thank you very much @tom-englert, it works perfectly :)
Much appreciated.
