### ISSUE TITLE
Keep letter casing in translation

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/ResXResourceManager#377]
Often translations are returned in a different letter casing than the original, for example the original is "TESTING" the translation in some languages may come back as "Testando" or "testando".
This is a difficult thing for mixed letter casings like in "Testing the CURRENT action" but could be solved automatically for all-equal casings like in "TESTING" or "testing", where most likely other languages use the same casing.

**Comment by tom-englert** [comment]
RXRM doesn't change the strings returned from the translation services.
You have to report that to the translation services you are using.

**Comment by Hefaistos68** [comment]
> RXRM doesn't change the strings returned from the translation services.
Of course it doesn't, but it might if an option was available.

**Comment by tom-englert** [comment]
If you think that's worth the effort, you can provide a PR.
