### ISSUE TITLE
Azure auth key not stored

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/ResXResourceManager#379]
**Describe the bug**
When i add a auth key for Azure translations and check the "Save credentials" , they are still not saved ever, next time I open the solution the key is gone and the "Save credentials" unchecked

**To Reproduce**
Enter a key for Azure translator, check the "save credentials", save everything, restart VS and load the solution back.

**Expected behavior**
Keys to be stored

VS 16.8.4 Community Edition (experienced in earlier versions too)

**Comment by tom-englert** [comment]
Only happened when focus is still on "save credentials" when closing.
