### ISSUE TITLE
New Key not saved after switch to new tab

### ISSUE THREAD

**Issue by edika99** [dotnet/ResXResourceManager#383]
When I insert a new key, and its translated strings (normally English and Italian), the key is saved but the two translations are not. I notice this only when I switch to another tab and then return to the Resx window, only then do I realize that the two translations are empty (with a red background).
Resx does not report any errors to me.
In order to save new keys I have to deselect the resource libraries I'm working on and then select them again. Only then are the new translations saved. When I change the window again and then go back to Resx this behavior often repeats itself.

**Comment by tom-englert** [comment]
You have to leave the row, e.g. by pressing the enter key, to submit the changes.

**Comment by edika99** [comment]
The solution provided is not working. even If I leave the row the new text is not saved.
Please watch the behaviour in a project [http://edika.net/public/resxmanbug.mp4](http://edika.net/public/resxmanbug.mp4)
