### ISSUE TITLE
Scripting module - A snapshot comparison (generating changes) - PROBLEM!

### ISSUE THREAD

**Issue by jovanmatic** [dotnet/ResXResourceManager#386]
Hello!

Today, I tested your Scripting module with a larger Solution (about 14k resources) and I think there is a problem in generating differences between the loaded snapshot and the Solution which is used for comparison.

At first, in my Solution there are 8 different columns-languages (EN - a neutral language, RU, DE, FR, ES, IT, KO and HU). Also, there is a translation (for all 7 non-neutral languages) for most resource from a neutral column (there are about 20-30 missing translations for every language) - the corresponding .resx files were generated using ResXManager extension in VS 2019.

The scenario was the following: 
1. I created a snapshot with ResXManager extension in VS 2019 for my current (latest version) Solution.
2. I ran the attached script (.ps1 script, [sample.txt](https://github.com/dotnet/ResXResourceManager/files/5893922/sample.txt)) in PowerShell ISE.
**IMPORTANT NOTE**: Meanwhile, I didn't make any changes to the resources and the translation in the whole Solution.
3. The expected number of changes was 0 because the state of resources and translations in the snapshot was equal to their current state in the Solution.
4. Unfortunately, I got the following result:
![screenshot2](https://user-images.githubusercontent.com/17766023/106277628-b8eb0500-6239-11eb-8627-a48e6f8ad598.JPG)

My questions:
1. Do you know exactly what the problem is, based on the described scenario?
1. Are you familiar with the behaviour of Scripting module when working with Solutions that have large amount of resources?

Thankful in advance for the reply.

**Comment by tom-englert** [comment]
Maybe there are orphan .resx files in your folder, that are not part of the solution?

**Comment by tom-englert** [comment]
@jovanmatic did you sort out what the differences where?

**Comment by jovanmatic** [comment]
Hi, again.

I checked for an orphan .resx files in my Solution and I didn't find any file of that kind (as validation: ResX Manager in VS shows 13970 resources and the script also shows 13970 resources). So, I think this part is valid.

But, I still have the same problem.

I tested more this problem, and I found the following:

A) If I generate a snapshot via script (not via ResX Manager in VS) and then generate the changes (the same scenario - without changes in entire Solution meanwhile), I will get different number of changes (not 4940):

![Script result](https://user-images.githubusercontent.com/17766023/107618461-e4b2b580-6c51-11eb-8695-c0ae138362d2.jpg)

Do you know anything about this behaviour?

B) If I generate an Excel file for all resources via script, I noticed that the certain number of resources (rows in Excel file) have "project" as value in the first column "Project", instead of the real name of the project. If I generate the Excel file for all resources via ResX Manager in VS, values in the first column are valid, all of them. On the following screenshots I have shown the differences. 

This is the result of generating the file, executing the script:
![Script](https://user-images.githubusercontent.com/17766023/107618842-84704380-6c52-11eb-8bf7-157aa3b307ad.jpg)

This is the result of generating the file via ResXManager in VS:
![UI](https://user-images.githubusercontent.com/17766023/107619027-cdc09300-6c52-11eb-831f-4fcf2fc1b3bf.jpg)

Can you now guess what the problem is in my case based on everything written?

Thankful in advance for the reply.

**Comment by tom-englert** [comment]
Since the scripting and standalone versions can't parse the solution/projects, the project is determined by the existence of the nearest `*.*proj` file. Maybe it does not find the `ProjectManagerCenter` project file? Or is there a file named "project.csproj"?

**Comment by jovanmatic** [comment]
Hi!

In File Explorer I typed '*.*proj' and searched for potentially problematic files. I found files with the following extensions:

A) .csproj
B) .saproj
I found a lot of files named 'project' with an extension '.saproj' (project.saproj - used by Smart Assembly) - this file was in almost every project in my Solution.

For testing purposes, I removed all of these files.

Via script, I repeated the scenarios from the previous post:

I generated the snapshot then I generated the changes (NOTE: I didn't make any changes in the Solution meanwhile (between snapshot and changes)). Now, I get different number of changes: 3660 (instead 3998).

After that, when I generated an Excel file for all entries, I got lower number of 'project' rows. But they are still exist. I tested several rows of that kind and in those appropriate projects I can't see any 'suspicious' file, which can make a problem. There are: .csproj file, .csproj.vspscc file, .config file and a lot of .cs, .designer.cs and .resx files.

C) .shproj
There are several Shared projects in my Solution. I checked every project of that kind and everything is good (a valid result in Excel file).

D) .projectProperties
These are internal files which are required for a build process. I think these files don't have a connection with a described problem. Or maybe I'm wrong?

Now, can you guess what the problem is in my case based on everything written?
Any other potentially problematic file type which I can check?

Thankful in advance for the reply.

**Comment by tom-englert** [comment]
Maybe you can try the standalone version, it uses the same loading procedure as the scripting module - so you can easier visualize the differences and find the root case for this?

**Comment by jovanmatic** [comment]
Hi!

I opened the ResX Manager extension in Visual Studio again and I can't spot what the problem is.

I still don't understand why Scripting module generates a lot of changes although I didn't make any change in the period between generating the snapshot and generating the changes.

Also, for testing purposes, I generated a snapshot via ResX Manager extension in Visual Studio and immediately after that I loaded it (the same scenario from the Scripting module). The ResX Manager extension showed no differences which is the expected behaviour.

**Obvious, the Scripting module and the ResX Manger extension in Visual Studio don't work identically.**

Also, I was looking at the changes in search for some rule (maybe some specific group of resources is problematic), but I didn't find anything unusual (in the previous posts I wrote everything I came across during testing my Solution with the Scripting module).

I don't know what to do right now! :(

Did you remember of anything else in the meantime that might be interesting for this case?

Thankful in advance for the reply.

**Comment by tom-englert** [comment]
> **Obvious, the Scripting module and the ResX Manger extension in Visual Studio don't work identically.**

Yes, as already stated above, the scripting module only scans the directory for *.resx and *.??proj files, while the VSIX uses Visual Studio to parse the solution and the projects.
That's the only difference, but if your solution and projects do not match the folder structure 1:1, this might be important.
The only advice I can give is, just don't mix both scripting and extension if your folder structure does not match your solution at 100%.

BTW, did you check the standalone GUI version of ResXManager? This uses the same directory scan engine like the scripting module, so they should be always compatible.
