### ISSUE TITLE
Reference not found in the code file

### ISSUE THREAD

**Issue by simonebonetto** [dotnet/ResXResourceManager#387]
Hi,

ResXResourceManager indicates that the StartReplay resource is used 0 times in the code. 
Instead it is used in a xaml like this:

`<RibbonButton LargeImageSource="pack://application:,,,/MyApp.Icons;component/Icons/Play.png" Label="{x:Static localstrings:Resources.StartReplay}" IsEnabled="{Binding EnablePlay}" Click="btnPlay_Click"/>`

I can also tell you that if instead I write the code as follows the resource is identified:

`<RibbonButton Label="{x:Static localstrings:Resources.StartReplay}" LargeImageSource="pack://application:,,,/MyApp.Icons;component/Icons/Play.png"  IsEnabled="{Binding EnablePlay}" Click="btnPlay_Click"/>`

Thankful in advance for the reply.

**Comment by tom-englert** [comment]
See #80, everything must be on one line for the regex to find it.
