### ISSUE TITLE
A better searching method

### ISSUE THREAD

**Issue by exuser** [dotnet/ResXResourceManager#388]
Hello,
I love Resx Manager, it is a great tool!

I have a particular large solution that has over 10k strings. Sometimes strings are duplicated, these can be due to the same UI in different places, or other reasons, for example, "Cancel" button is in two forms. Resx will show both on the list. I can copy the values from an entire row into the row without values.

The problem is that to go through all missing items by scrolling down, is a big task (hours). It crashes as well (especially after working with it for over 10-15 minutes without restart). The key is that **I need one line with existing values and one with the blank ones** in order to copy paste between them.

What i do currently is: I search in the relevant language $^ for empty rows, then copy all values from the Neutral language into a notepad. Then i search one by one (or a few multiple ^(string1|string2|string3) so i can have lines with values and lines without, to copy and paste between them.

I would love a method that can display empty lines (e.g. $^) + one line above it and one under it. This automation would save a lot of time!

**Comment by tom-englert** [comment]
Just switch to the "Translate" tab - it will instantly offer you all existing translations for empty items with the same neutral value.

**Comment by tom-englert** [comment]
@exuser did that solve your problem?

**Comment by tom-englert** [comment]
Closed as stale
