### ISSUE TITLE
Wrong filename when adding resource file

### ISSUE THREAD

**Issue by MikeFH** [dotnet/ResXResourceManager#390]
**Describe the bug**
Adding a resource file via the "add new language" can lead to file names with 2 culture keys like Resource.de.fr.resx

The cause seems to be that the `GetLanguageFileName` method assumes it receives a filename without culture key.

**To Reproduce**
* Create a directory with a single resx named Resources.de.resx
* Open the directory in the application
* Add a new language (for example fr) and add a new key in the new language to cause the file creation
* The new file is named Resources.de.fr.resx
* This causes the resource to appear 2 times in the list on the left (named Resource and Resource.de)

**Expected behavior**
The file should be named Resources.fr.resx

**Comment by tom-englert** [comment]
Resx always require a neutral resource file (https://docs.microsoft.com/dotnet/api/system.resources.resourcemanager)
