### ISSUE TITLE
Detect code reference does not find any coincidences in *.aspx files

### ISSUE THREAD

**Issue by trullanine** [dotnet/ResXResourceManager#391]
Dear collaborators,

I am trying to count code references for all keys but it does not seem to work with *.aspx files. I have checked the regex expression and even made as simple as "match this very specific key" but it always finds 0 references.

I have an aspx file with the following line:
`<input type="hidden" id="PowerText" value="<%=Resources.gb_Sie.val_potencia%>"/>`
File: **gb_Sie**
Key: **val_potencia**

I have tried with the folowing regex: \%=Resources\.($File)\.($Key)%

![imagen](https://user-images.githubusercontent.com/78925316/107675404-5f062880-6c98-11eb-9221-5fe6b8359f9e.png)
![imagen](https://user-images.githubusercontent.com/78925316/107674684-7e508600-6c97-11eb-985f-b68535771f68.png)

As it hasn't worked: I have tried to find the key directly in any aspx file with the following expression: ($Key)
As it hasn't worked, I have tried to find the specific key directly with the following "expression": val_potencia

The result is always the same. I assume it's not parsing the file at all, as it does work on a regex tester.
![imagen](https://user-images.githubusercontent.com/78925316/107674483-4d705100-6c97-11eb-9d4c-ccfd8c2fa023.png)

The aspx files are in the same directory as the *.vb files, which do work fine with the Code Reference finder.

Did anybody have the same issue? Am I doing something wrong or is it a bug?

**Comment by tom-englert** [comment]
Can you share a small sample project to reproduce this?

**Comment by trullaninergy** [comment]
Please find a test project attached with two translations "val_IGICReduit" and "val_potencia".

ResXResourceManager can find the key "val_IGICReduit", that can be found in the .vb file, but cannot find the key "val_potencia", that can found in the .aspx file, even if I force the regular expression to match directly "val_potencia"

[test.zip](https://github.com/dotnet/ResXResourceManager/files/5973065/test.zip)

**Comment by tom-englert** [comment]
Works great when I use e.g. just `Resources\.($File)\.($Key)` as the pattern:

![image](https://user-images.githubusercontent.com/10229954/107844658-a514d680-6dd5-11eb-8e0c-35736194309d.png)

**Comment by trullanine** [comment]
Dear Tom,

Many thanks for your help! I tried it and, at first, it didn't work for me. Then I saw this warning:
![imagen](https://user-images.githubusercontent.com/78925316/107924398-28b7fa00-6f73-11eb-91a9-63ec8ce85273.png)

When I closed the solution and I changed the pattern in the default config, it did find the references.

May it be a bug?

Best regards,
Toni

**Comment by trullanine** [comment]
Not sure if it is what I posted this morning, because I'm trying to match other patterns and I have similar problems. To me, it seems like when I change the config, the change is not applied or saved. It's a bit frustrating. 

If I can reliably reproduce the issue, I'll post more precise steps.

**Comment by trullanine** [comment]
Okay, I am pretty confident it has to do with unsaved changes. For example, when I try to match:

- the key "txt_arxiuEliminat" 
- in a .vb file
- using the following pattern: \W($Key)\W
- having deleted the "comment token"

It only finds a reference in the code, when I manually remove the comment token in the .vb file. However, according to the config I just changed, there is no "comment token"

![imagen](https://user-images.githubusercontent.com/78925316/107978436-0cd94600-6fbd-11eb-9fda-f4078e7dfee8.png)

The line where the key can be found is the following:
`"BootBoxAlert($('#DeleteTitle').val(), $('#Aceptar').val(), """ & String.Format(Resources.gb_Sie.txt_arxiuEliminat, nDeletedDocs) & """, 1, actionButton)",`

**Comment by trullanine** [comment]
@tom-englert could you reproduce the issue?

Thank you very much.

**Comment by tom-englert** [comment]
No, sorry, maybe you can try to debug this by your own?

**Comment by tom-englert** [comment]
No more feedback, and not reproducible - closed as stale
