### ISSUE TITLE
[BUG] Written text disappears while typing

### ISSUE THREAD

**Issue by krzysztofrosol** [dotnet/ResXResourceManager#402]
I love your tool, but now there is the most annoying bug ever.

Let say you have 3 resources: Neutral, English and Polish.
You have provided a Neutral text. OK
You have copied Neutral to English. OK
You start to typing a resources for Polish. After few characters a magic happens. 
**Polish text has been removed and typing is started again.** CTRL-Z does not work.
English resources has been deleted but after i press Enter this resources comes back again.

The same magic happens if you try to change resources.

I use a fresh installation of Windows + VS 2019 v.16.9.2 + ReSharper + TFS Plugin (not GIT).
Configuration is default. Main tab => comment column is hidden + allow select individual cells enabled.
I think that there is some magic thread in background that reloads resources. It should skip edited resources I think.

To test your solution try write something (a longer text), other than random key-press and copy and paste.

**Comment by krzysztofrosol** [comment]
To avoid this issue, and many more, please do not upgrade VS 2019 above version 16.6.5. The latest versions breaks RESX and even Resharper.

So the my suggested workaround is to downgrade VS 2019 to v.16.5.5.

**Comment by tom-englert** [comment]
Thanks for the investigation. Did you already raise an issue for Visual Studio?

**Comment by tom-englert** [comment]
I just tried with VS 16.9.1, but can't reproduce this...

**Comment by tom-englert** [comment]
Looks like this was a Visual Studio problem that is solved now.
