### ISSUE TITLE
DteSolution.GetProjectFiles is causing UI lockups

### ISSUE THREAD

**Issue by davkean** [dotnet/ResXResourceManager#403]
**Describe the bug**
Hey I'm from the Visual Studio performance team, and according to our telemetry, `DteSolution.GetProjectFiles` is causing UI lockups, very likely due to spending large amounts of times walking every file in every project.

**To Reproduce**
This is based on telemetry from real world solutions, there is no repro.

Our telemetry shows that the 75th percentile of this delay is 2 seconds, but some users experience delays of upwards of 60 seconds, and very often occurs within the first minute after solution load, or while the user is debugging. This has interrupted 900 mouse (sampled) events over the past 21 days.

Frame|Hit Count|75th Percentile Duration
 -- | -- | --
resxmanager.vsix.dll!ResXManager.VSIX.DteSourceFilesProvider.GetProjectFiles | 19,179 | 2.12 sec

**Expected behavior**
I'm not entirely sure of the scenario, but this feature should be written in a way that avoids walking every file in every project. 

Can you explain what you are trying to do and I can give some advice?

**Comment by tom-englert** [comment]
@davkean The core feature of this project is to show the content of all resource files (*.resx, *.resw) of the whole solution.
Another feature is to detect usages of the resource entries in all source files.
This is why the project needs to walk all files of the project, and group them by file type; the resource files will be shown in the editor, and the source files will be scanned for usages.

Maybe there is a better way getting this info, especially one that can be called async?

**Comment by tom-englert** [comment]
@davkean I managed to defer the call to `DteSolution.GetProjectFiles` until it's really needed, i.e. until you open the tool window or use a feature related to resource files. 
So it should at least no longer have an impact on the solution loading time.

**Comment by tom-englert** [comment]
@davkean anything else we can do to improve the UX here?

**Comment by tom-englert** [comment]
@davkean @madskristensen should I close this? 
I did not find a good way to enumerate all files asynchronously - I found `GetAllProjectsAsync()` in the `Community.VisualStudio.Toolkit`, but no `GetAllFiles...` at the `Project` level.

**Comment by madskristensen** [comment]
I believe that all IVsHierarchy interactions are blocking the UI thread, so there is no way to do this in the background

**Comment by tom-englert** [comment]
OK, so deferring the enumeration as long as possible is all we can do here, so I close this issue.

**Comment by tom-englert** [comment]
So there is nothing left that we could improve here.
