### ISSUE TITLE
Translated text not saved

### ISSUE THREAD

**Issue by edika99** [dotnet/ResXResourceManager#404]
I have to reopen the iissue #383 because the solution provided is not working.

Please watch the behaviour in a live example [http://edika.net/public/resxmanbug.mp4](http://edika.net/public/resxmanbug.mp4)

As you can see I leave the row as suggested and I switch to a diffeent tab. When return to Resx tab the new text is not present anymore.
The onyl way to save new text is to close the Resx windows and then reopen it. Resx start work correctly after some new entry, the prblem starts again.

**Comment by tom-englert** [comment]
I can't reproduce this - looks like some other thread is reverting your changes. Can you check this:
- Are the changes saved to the .resx file when you commit a row?
- Does the file change back to the previous state at some point?

**Comment by edika99** [comment]
Because this behaviour is intermittent, as soon is happening again I will made these check.

**Comment by tom-englert** [comment]
Maybe it's related to #402?

**Comment by edika99** [comment]
No it isn't. Today is ahppen again so I've monitored the Resx File. The 2 new keys where not added, and I was writing the localized text only in Italian , not int the neutral. Switching tab, the text has been deleted but the key was there even if in the Resource.it.resx file the keys was not there. A s soon as I write the text in neutral language the 2 new keys has been written in the Resource.it.resx . Unfortunately I was monitoring only the Resource.it.resx file and not the Resource.resx.
Next time I will open also the Resource.resx to check if at least the new keys is added to the file.

**Comment by edika99** [comment]
Today I also had the opportunity to check the Resource.resx file.
When the problem occurs, the key is added to the Resource.resx file but not those of the other languages. The text, on the other hand, is obviously not written to the file.
This time I managed to solve the problem without closing the ResxManager: I saved all the files opened with CTRL + Shift + S and as soon as I did this I saw that the Resource.resx file has been modified, inserting the new text, and the files of the other languages have also been updated.
I don't know if saving open files with changes has any connection with ResxManager, but this is what I found.

**Comment by tom-englert** [comment]
Looks like some other tool is caching the resource files without opening them. Files that are opened as document, like the built-in resource editor does, are detected by ResXManager: 
![image](https://user-images.githubusercontent.com/10229954/115897329-96ddd900-a45c-11eb-8b9d-f48a6efeea32.png)

**Comment by tom-englert** [comment]
Looks like this problem is not caused by ResXManager itself - so nothing we can do about.
