### ISSUE TITLE
Response status code does not indicate success: 400 (Bad Request)

### ISSUE THREAD

**Issue by Outworldz** [dotnet/ResXResourceManager#412]
Hi Tom: What a lovely product! I used to use Google sheets to handle about 15,000 rows in 20 languages.  Now I can do 30 languages easily.  That is, when it works.  Both Google and Azure give me the above error message 9 times out of 10, or 10 out of 10 on different machines.  I wait a few minutes, and it may work for 20 rows or all rows, or not work today.   Src is always English to 30 languages.  Small batches of them need to be added  every few weeks. 

Google reports API errors in their translation API, 65% of them this last attempt.  It doesn't say what.  Same error on Azure.  I am on  Visual Studio latest build, and I have uninstalled Resx and re-installed it on 3 machines multiple times.   Not sure how what else I can say, other than its really a great thing you have done here.

**Comment by tom-englert** [comment]
Maybe you've exceeded your limits? 
Anyhow there is nothing ResXManager can do about that, at least if the service does not  respond with a useful error message.

**Comment by Outworldz** [comment]
I understand. But there is no limit on my account, and I've worked with the translator API over many years with both Azure and Google for dozens of applications, with hundreds of thousands of users.  

After writing the above, it spent about an hour not running as I checked it periodically. Then Azure suddenly ran once, then Google ran perfectly for several runs. It's hardwired gigabit on a 100/100 net on I9/9900K.    Wireshark does not help, as its encrypted *sigh*  It shows 10% error rate at Google.

**Comment by tom-englert** [comment]
I don't even have a Google account, so I can't test this. It was a contribution by @dahall and @burukan, maybe they can help you?

**Comment by burukan** [comment]
Just saw this.... I would imagine this being either a throttle error or text specific (maybe some lines being too long? google had a 5000 character limit afaik). The service should have returned a "message" but I will see if I could extract any part of it or if its possible to skip that item/batch.
