### ISSUE TITLE
Marketplace, minor typo at the bottom

### ISSUE THREAD

**Issue by Countryen** [dotnet/ResXResourceManager#413]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
At the bottom the page says "Powerd by (ReSharper)" instead of "Power**e**d by (ReSharper)".
Could be desired, but on the GitHub page it says it "Powered" so I assume this is a typo.

**To Reproduce**
Look at the page at the bottom on the right.
https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager&ssr=false#overview

**Expected behavior**
The text says "Powered by (ReSharper)".

*Note: I didn't know where to find this page here in the codebase otherwise I'd just create a small PR instead.*

**Comment by tom-englert** [comment]
Thanks!
