### ISSUE TITLE
Support Visual Studio 2022 v17.0

### ISSUE THREAD

**Issue by tom-englert** [dotnet/ResXResourceManager#415]
The Visual Studio extension should run in VS 2022

**Comment by tom-englert** [comment]
@madskristensen I've managed to get it starting in `Version 17.0.0 Preview 1.0` (https://github.com/dotnet/ResXResourceManager/tree/VS2022), but all calls to DTE fail with a `System.MissingMethodException`. 
Looking at the `EnvDTE*.dll` with ILSpy shows that they are really empty assemblies with no methods.

Is DTE supposed to be supported, and this is just a limitation of preview 1, or will there be a replacement for DTE?

**Comment by madskristensen** [comment]
Use DTE2 exclusively

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tom-englert** [comment]
@madskristensen Thanks for the hint, but that fixed only one, these still fail:

```
Error: ConnectEvents:System.MissingMethodException: Method not found: 'Void EnvDTE._dispSolutionEvents_OpenedEventHandler..ctor(System.Object, UIntPtr)'.
   at ResXManager.VSIX.VsPackage.ConnectEvents()
```

https://github.com/dotnet/ResXResourceManager/blob/6a45666ba20a623b426a0125d783f79894af4a7a/src/ResXManager.VSIX/VSPackage.cs#L207-L224

**Comment by madskristensen** [comment]
Looks like it's using the EnvDTE and not EnvDTE80 under the hood somewhere `EnvDTE._dispSolutionEvents_OpenedEventHandler`. If you can't pinpoint it, you may have to split your extension into two. My YouTube live stream today will be about how to do that for VS 2022

**Comment by tom-englert** [comment]
But then how to correctly connect to that events in VS2022?

**Comment by madskristensen** [comment]
That should work, but you should be using `Microsoft.VisualStudio.Shell.Events.SolutionEvents` for that use case. That will work

**Comment by tom-englert** [comment]
OK, thanks, that did the trick for some of the solution events, but how to get hold of these?
https://github.com/dotnet/ResXResourceManager/blob/6a45666ba20a623b426a0125d783f79894af4a7a/src/ResXManager.VSIX/VSPackage.cs#L248-L250
https://github.com/dotnet/ResXResourceManager/blob/a902e69b95d3a505ac4aa30fb3bc4c3ce1fa75d8/src/ResXManager.VSIX/ErrorProvider.cs#L55-L62
I could not find anything in the shell.

**Comment by tom-englert** [comment]
@madskristensen Tried `Community.VisualStudio.Toolkit.VS.Events`, but I get the same error.

**Comment by madskristensen** [comment]
The underlying interop types behind those DTE events might have changed with VS2022 and not be backwards compatible. You may have to split your extension. You could try to do this to capture any document events.

```csharp
var rdt = new RunningDocumentTable();
rdt.Advise(this); // Free from memory, might be slightly differnet
```
