### ISSUE TITLE
Error adding any new resources

### ISSUE THREAD

**Issue by aidanhorton** [dotnet/ResXResourceManager#416]
**Describe the bug**
Whenever I try to add a new language, then either manually add a resource, or try to apply auto-translations, I get the following error message:
![image](https://user-images.githubusercontent.com/22588585/125065440-b83c8180-e0a9-11eb-9039-38da21963143.png)

I would expect when a resource file is added that it adds a reference to the resource file on the project too, but in most cases it just adds the file but it doesn't show up in solution explorer because they don't get referenced in the CSPROJ files - see below pending changes in Git:
![image](https://user-images.githubusercontent.com/22588585/125065577-e15d1200-e0a9-11eb-80ad-cd029166b597.png)

**To Reproduce**
Add a language.
Add a resource manually -> ERROR
Apply an auto-translation -> ERROR
Some resource files are created but not referenced by CSPROJ files.

**Expected behavior**
The resource files are added and referenced in the solution explorer!

**Comment by tom-englert** [comment]
As you can see from the call stack, the exception is thrown by Visual Studio.
ResXManager tries to add the file to the project, but Visual Studio fails to process the request.
Usually a restart of Visual Studio helps to fix `ProjectItem unavailable` issues.
If the problem persists, raise an issue for Visual Studio.
