### ISSUE TITLE
Haitian Creole (ht) is not available  

### ISSUE THREAD

**Issue by nullstatement** [dotnet/ResXResourceManager#417]
**Describe the bug**
Haitian Creole (ht) is not a language that is available to be selected in the languages tab.

**To Reproduce**
Either navigate to the languages tab or select add new language.
Haitian Creole is not an option.

**Expected behavior**
Expect to see "ht - Haitian Creole" as an option in both the languages tab and the add a new language dialog. 
The flag is already saved in the repository https://github.com/dotnet/ResXResourceManager/blob/master/src/ResXManager.View/Flags/ht.gif

**Comment by tom-englert** [comment]
ResXManager supports all languages that you current  .Net Framework installation supports. 
Raise an issue for the .Net Framework to add your requested language, and it will be supported by ResXManager out of the box.

**Comment by tom-englert** [comment]
P.S. see https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultures

**Comment by nullstatement** [comment]
Thanks!

**Comment by onionhammer** [comment]
@tom-englert 
It seems like Haitian creole is available:

![image](https://user-images.githubusercontent.com/969938/206030494-2097cfa5-0d5b-4b45-9611-8774bd059c29.png)

**Comment by onionhammer** [comment]
@tom-englert interesting... I had no idea this system was so complex. It's weird that translation services such as google and azure translate support HT but not windows/.NET ?
