### ISSUE TITLE
Adding a new key doesn't move the keyboard focus to the new key

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/ResXResourceManager#419]
**Describe the bug**
After adding a new key with <kbd>Shift</kbd>+<kbd>Insert</kbd>, the newly added row is selected, but the keyboard focus is still on the previously selected row.

**To Reproduce**
1. Have a long list of keys.
2. Move the keyboard focus to one of the keys (preferably far away from the key you're going to add).
3. Press <kbd>Shift</kbd>+<kbd>Insert</kbd> and type the name of the new key and press <kbd>Enter</kbd>.
4. Notice that the row of the newly added key is selected.
5. Press <kbd>&uarr;</kbd> or <kbd>&darr;</kbd>.
6. Notice that the selected row is now the key above/below the key from step 2.

**Expected behavior**
When pressing <kbd>&uarr;</kbd> or <kbd>&darr;</kbd> in step 5, the selected row should be the one above/below the newly added key from step 4.

**Comment by tom-englert** [comment]
That's the default behavior for the WPF data grid; moving the selection via code does not automatically move the focus.
I'm happy to accept your PR if you like to have something more sophisticated,
