### ISSUE TITLE
Up arrow moves the keyboard focus into the filter textbox, but down arrow doesn't move it out

### ISSUE THREAD

**Issue by JeroenOortwijn** [dotnet/ResXResourceManager#420]
**Describe the bug**
When you move the keyboard focus up through the list of keys, you eventually end up at the first key in the list.
When you now press <kbd>&uarr;</kbd> again, the keyboard focus moves to the filter textbox in the column header.
But when you then press <kbd>&darr;</kbd>, the keyboard focus stays in the filter textbox.

**To Reproduce**
1. Have a long list of keys.
2. Select one of the keys in the middle of the list.
3. Keep <kbd>&uarr;</kbd> pressed.
4. Notice that the selection moves upwards until it is at the first key.
5. Notice that the filter symbol located in the column header now changed to a textbox with a blinking cursor inside.
6. Press <kbd>&darr;</kbd>.
7. Notice that the selection doesn't change and the textbox with the blinking cursor is still visible.

The only way to get the keyboard focus on the selection again, is to press <kbd>Tab</kbd> several times.

**Expected behavior**
- Either keep the keyboard focus on the selected key and don't move it to the filter textbox in the column header.
- Or, if the moving to the column header is a feature, move the keyboard focus out of the filter textbox and onto the selected key when pressing <kbd>&darr;</kbd>.

**Comment by tom-englert** [comment]
That's the default WPF behavior; up and down keys in a text box have no focus action.
I'm happy to accept your PR if you like to have something more sophisticated,
