### ISSUE TITLE
.NET6 Unable to Move to Resource

### ISSUE THREAD

**Issue by hyperworkxdevteam** [dotnet/ResXResourceManager#435]
Using VS Pro 2022 with .NET 6.0 with ResXManager Version 1.61.4637.0, I lost the possibility to "Move to Resource" when I right click on a text in a .cshtml file. In the .CS fil I am able to do a right click. and "Move to Resource

if I change the Target framework to .NET 5.0 I have no issues and the feature works perfect. 

Furthermore, Love the ResXManager!

**Comment by tom-englert** [comment]
Can you try this: https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a

**Comment by hyperworkxdevteam** [comment]
Yes this works perfect!
Thank you very much!
