### ISSUE TITLE
Text template code generator not working in VS 2022

### ISSUE THREAD

**Issue by hawelo** [dotnet/ResXResourceManager#437]
**Describe the bug**
Code generator fails with following errors when using Text template in VS 2022 (.net5 or .net6):

 The type 'DTE' exists in both 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The type 'ProjectItem' exists in both 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The type 'DTE2' exists in both 'EnvDTE80, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**To Reproduce**
1. Create new Console app in VS 2022 (.net 6).
2. Add new Resource file.
3. Open ResX Resource Manager and change Code generator from Custom tool to Text template.

**Expected behavior**
Text template code generator works.

**Comment by tom-englert** [comment]
Maybe the template was already existing and you did not update it?

**Comment by hawelo** [comment]
I can reproduce it in a new solution and project, so I don't think it will be the case.

However I can fix it by editing the T4 template. It works fine if I remove lines:
```
<#@ assembly name="EnvDTE" #>
<#@ assembly name="EnvDTE80" #>
```
and replace them with the following line:
```
<#@ assembly name="Microsoft.VisualStudio.Interop"#>
```

**Comment by tom-englert** [comment]
The original template is used by RXRM itself, and here it works fine. 
Also with a new project in a new solution it works fine.
What version of VS do you have installed?

**Comment by hawelo** [comment]
I'm using Visual Studio Enterprise 2022 Version 17.0.1.

**Comment by tom-englert** [comment]
I'm using 17.1.0 Preview 1.0
I also had problems in the first place, but that had been already fixed in one of the previews of VS17: https://developercommunity.visualstudio.com/t/t4-templates-in-vs2022-require-incompatible-usings/1472620?from=email&viewtype=all#T-ND1561602

**Comment by tom-englert** [comment]
Anyhow this is more a VisualStudio issue, and if you don't need to run it on VS2019, you already have the workaround.
