### ISSUE TITLE
After VS update all settings lost

### ISSUE THREAD

**Issue by GuruMedi** [dotnet/ResXResourceManager#441]
After Visual Studio update. The DeepL API-Key and API-Url are lost.

**Comment by tom-englert** [comment]
These are stored in the user settings of VS, and I see no way to tell VS to migrate those.

**Comment by jakehedlund** [comment]
@tom-englert If the Properties.Settings.* API is being used, you can try this: https://stackoverflow.com/a/982397 (buried in a comment by jasonh)
 
All it takes is creating an extra boolean property called `upgradeNeeded` (default to true). Then at the start of the app do the following: 

```
    // Migrate settings
    if (Settings.Default.upgradeNeeded)
    {
        Settings.Default.Upgrade();  
        Settings.Default.Save();
        Settings.Default.Reload();
        Settings.Default.upgradeNeeded = false;
        Settings.Default.Save(); 
    }
```

It looks like VS does store settings in a `user.config` file so this should work. 
`C:\Users\[user]\AppData\Local\Microsoft_Corporation\DefaultDomain_Url_k4lj1j1uo5qykqsaw5f0gpihluyfba1t\17.2.32516.85\user.config`
