### ISSUE TITLE
A few remarks on the English (en-US) translation template (plus a Swedish translation)

### ISSUE THREAD

**Issue by Lakrits** [dotnet/ResXResourceManager#445]
### Remarks on the English (en-US) translation template

_**a) Common issue**_
Lack of consistency in use of the name of the program. It is referred to as both "ResX Resource Manager" and "ResX Manager".

_**b) Directory specific issues**_
The entries below follow the systematic structure found in ResX Resource Manager. I have formatted them as follows:

**Directory - Folder\File**
Index #
`Key`

> String

Comment: My comment

**ResXManager - Properties\Resources**
4
`Version`

> Version: {0}

Comment: Invariant. Shouldn't this string be made available for translation?

**ResXManager.View - Properties\Resources**
5
`CaseSensitive`

> Case Sens.

Comment: Invariant. Shouldn't this string be made available for translation?

35
`EditDefaultConfigurationNotification`

> Your are editing the default configuration /.../

Comment: "Your" should be "You".

72
`ResourceFilterToolTip`

> /.../
> The pattern will be compared against the string "{project} - {folder}\{file}",
> which is the same as the group header in the grouped view 
> /.../

Comment: Needs full stop at the end of the sentence.

92
`TranslationsPrefixHeader`

> Prefix translations with

Comment: Needs trailing whitespace. Output is 'Prefix translations with"#TODO#_"'.

**ResXManager.VSIX - VSPackage**
1
`112`

> Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

Comment 1: Invariant. Shouldn't this string be made available for translation?
Comment 2: "ResX-Based" should perhaps be "ResX-based" or "ResX based"
Comment 3: "let's" should be "lets".

### Swedish translation
I have translated ResX Resource Manager into Swedish. It has been attached to this post as "[ResXRM_sv.zip](https://github.com/dotnet/ResXResourceManager/files/7834982/ResXRM_sv.zip)". Since I don't know how to work in GitHub (forking, pulling requests, and whatnot), I'll just provide it like this. Implement it if you think it may be of use to you.

### Disclaimer (of sorts)
I use the standalone version of ResX Resource Manager, and know next to nothing about coding and software development. Perhaps that is relevant to some of my remarks.

**Comment by tom-englert** [comment]
@Lakrits fixed the resources according to your review
The invariant entries only appear in logs, they should stay neutral.

Will you be able to maintain the Swedish resources in the future? It's usually only a few strings per year.

**Comment by Lakrits** [comment]
@tom-englert 
I'll be able to manage the translation for now, and will notify you if I have to step back (there are some health issues). The translation is good enough to be the basis for someone else. It conforms with Microsoft's Swedish terminology database, and with the Swedish translation of Visual Studio.
