### ISSUE TITLE
Add an option to set #TODO flag in the comment field, instead of on the value field

### ISSUE THREAD

**Issue by justinswork** [dotnet/ResXResourceManager#446]
### Scenario
One of the last steps in our software release process is to send out all of the strings that were added/changed since last release to our translators. However, since it can take quite a while for us to hear back from them, we usually have to send out the translations sooner rather than later, so that it doesn't hold up the release date. 

The problem is, sometimes we will need to make a few minor tweaks between sending out the translations and shipping the software. In this scenario, we are ok keeping the strings as "auto-translated", until the next release. When we do this, we put a TODO in the comment field, instead of the value so that we don't accidentally ship with TODO strings in the software.

### Feature Request
It would be great if there was an option to automatically prepend the TODO in the comment field instead of the value. We would actually use this option all the time so that we never had TODOs visible in the software, but we could easily find strings that need to be translated by filtering just on the comment field.

### Notes
While our scenario as described above works for the most, it relies on the development team remembering to do this manual step, which is a potential source of error.

**Comment by tom-englert** [comment]
Maybe you could simply use the scripting module to move the "TODOs" in the values to the comments?

**Comment by justinswork** [comment]
@tom-englert I'm afraid I'm not familiar with this scripting module, but I'd like to learn more. Could you offer any tips on how I would get started with something like that?

**Comment by justinswork** [comment]
I did some digging and found the scripting files. After briefly poking around with it, I really like the idea of using that to find the diff between two snapshots, and only export those changes.

While writing a script as you suggested would most likely help, I still think that would be too manual of a process to remember to run that script whenever necessary. I could be wrong, but it just seems like another step that would have to be documented in our release process, and another source of potential error.

I do really appreciate the suggestion, hopefully we can get some useful functionality out of it!

**Comment by tom-englert** [comment]
I'm happy to accept your PR if you like to see something like this integrated.

**Comment by justinswork** [comment]
Sounds good, I'll look into it

**Comment by justinswork** [comment]
I put up #447 
In all my years of programming, I've never taken the opportunity to contribute an open-source project before, so this was rather enjoyable! :)
