### ISSUE TITLE
Could not find any strings in Visual Studio 2022.

### ISSUE THREAD

**Issue by soultower17662079** [dotnet/ResXResourceManager#453]
I am using Visual Studio 2022 in windows10 LTSC 21H2. When I open a project, ResXManager can't find any strings. I changed the computer or reinstalled a windows 10 and it didn't solve the problem.

**Comment by tom-englert** [comment]
Can you share a sample project?

**Comment by soultower17662079** [comment]
https://drive.google.com/file/d/18rY9JF-ZLGjg4BYUynoDxQw8CToG0lrV/view?usp=sharing
Thank you very much for your reply. I have shared a project. Please check it out. I can't get any strings.

**Comment by tom-englert** [comment]
Well, this project does not contain any string resource, so what did you expect?

**Comment by soultower17662079** [comment]
I mean in previous versions it was possible to get some strings automatically. For example, the text of the text attribute of the label.
like this:
https://photos.app.goo.gl/GbzbLTctHgcjT3R1A

**Comment by tom-englert** [comment]
If you want to localize WinForms, you must set Localizable=true on every form.

**Comment by soultower17662079** [comment]
Aha, yes it is. I'm very sorry to bother you. This tool is really useful. Excellent!

**Comment by soultower17662079** [comment]
I don't know if you have a sponsorship channel like Alipay. I can't make payments on paypal!

**Comment by tom-englert** [comment]
You can try https://github.com/sponsors/tom-englert
