### ISSUE TITLE
does not save and show me the red line

### ISSUE THREAD

**Issue by KevinAnass** [dotnet/ResXResourceManager#454]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
when I write in the ResXManager tool for the first time it works fine but the second line does not save and show me the red line

**To Reproduce**
- write the first line and move to another tab 
- go back and write again another line and move to another tab when you come back it will show you the red line 
- 
![Capture](https://user-images.githubusercontent.com/59505755/153478495-6c727051-8d82-4ed0-995c-5b0f16278bf2.PNG)

**Expected behavior**
save the words i write

**Comment by tom-englert** [comment]
No response, closed as stale
