### ISSUE TITLE
Updated Swedish translation

### ISSUE THREAD

**Issue by Lakrits** [dotnet/ResXResourceManager#455]
### Update to the Swedish translation and small bug report
**Updated language files**
Here are the updated Swedish language files, conveniently packaged as a ZIP file: [ResXRM_sv.zip](https://github.com/dotnet/ResXResourceManager/files/8054217/ResXRM_sv.zip).

**Bug: Swedish language files empty in master repository**
When I downloaded the master repository to translate the new strings, I noticed that all the Swedish language files were empty, and didn't show in ResX Resource Manager. I had to use my own backup.

_-- Lakrits --_

**Comment by tom-englert** [comment]
Sorry, manually fiddling with single files is nothing I can handle.
