### ISSUE TITLE
Country code for Slovenia incorrect: sl instead of si

### ISSUE THREAD

**Issue by ralf-dlf** [dotnet/ResXResourceManager#458]
In ResXResourceManager the country code for Slovenia is mentioned and defined as "sl" (in uppercase: "SL")
However, the correct country code according ISO-3166 is "si" (uppercase: "SI") 

=> The appropriately created resource file ends with "sl", too: e.g. Resources.SharedResource.**sl**.resx

**To Reproduce**
Open the country list and look for entry Slovenia

**Expected behavior**
Resource file ends with "si"

![CountryCode_Slovenia](https://user-images.githubusercontent.com/98759656/153898475-568fd048-5f08-4a09-a32a-e8b9cd6fd99b.png)
![CountryList_Slovenia](https://user-images.githubusercontent.com/98759656/153898500-b371e508-fee1-4c85-9cef-bf8c1eef1e9f.png)

**Comment by tom-englert** [comment]
This list is provided by the operating system (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo)

If this is wrong you need to raise an issue for Windows or DotNet runtime.

**Comment by ralf-dlf** [comment]
Oh - I see.
Thanks for this information - I wasn't aware of that...

BR Ralf
