### ISSUE TITLE
Support for .resw files

### ISSUE THREAD

**Issue by mangoepic** [dotnet/ResXResourceManager#461]
**Is your feature request related to a problem? Please describe.**
I wasn't able to open .resw files yet and wondered if they're supported by the extension already?
I tried renaming them to a .resx file but they didn't show up in the ResX Resource Manager Window either.

**Additional context**
<details>
<summary>Screenshots</summary>

![grafik](https://user-images.githubusercontent.com/71931749/154708358-4f03c01e-2350-45fd-8132-768a3d312981.png)

![grafik](https://user-images.githubusercontent.com/71931749/154708406-dbc96d8b-08a7-46e2-aad8-f6a92c5ec09e.png)
</details>

**Comment by NJM-Goals** [comment]
Maybe you need to have a second dot in the filename, like it is necessary with .resx files. Like so:
texts.en-US.resx

**Comment by mangoepic** [comment]
> Maybe you need to have a second dot in the filename, like it is necessary with .resx files. Like so: texts.en-US.resx

this workaround works, thank you for the pointer

**Comment by tom-englert** [comment]
Rules for resw naming is different:
https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#localize-the-string-resources
