### ISSUE TITLE
Using DTE2 with VS2022

### ISSUE THREAD

**Issue by LesterSmith** [dotnet/ResXResourceManager#462]
I am trying to use DTE2 with VS2022 with the following code:

DTE2 dte = (DTE2)ServiceProvider.GetService(typeof(DTE2));

GetService has red line under it and the error is 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'ServiceExtensions.GetService<TService, TInterface>(IServiceProvider, bool)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	TestClassifier	C:\VS2022 Projects\Extensibility\TestClassifier\TestClassifier\TestDTE.cs	98	

I have tried everything.  The code is used in a  synchronous command on the Main UI Thread.

Thanks for any help.

**Comment by tom-englert** [comment]
Looks like you are using the wrong 
`ServiceProvider`
