### ISSUE TITLE
Add new language => automatically generate xliff files

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/ResXResourceManager#465]
When adding a new language, I would like all xliff files to be generated so we can immediately send them to translators.

At the moment, when adding a new language, the xliff are only added when we add something to the file first. Preferably I would like to have a new xliff with all status to be translated.

**Comment by tom-englert** [comment]
Checking "Create all resource files..." in the configuration may fix this...

**Comment by tom-englert** [comment]
OK, I'll have a look, probably there is no "save" event when the new files are generated.
