### ISSUE TITLE
VSPackage did not load correctly

### ISSUE THREAD

**Issue by DavidStania** [dotnet/ResXResourceManager#466]
Hello,
I'am getting an exception in VS2022 17.1.1 64bit after installation ResX and restarting VS.

![image](https://user-images.githubusercontent.com/27513913/158975899-c561ec4a-b246-4305-b75e-f0bdfb42bb40.png)

This log contains the following informationen:

> SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Mindestens ein Typ in der Assembly kann nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie weitere Informationen ben&#x00F6;tigen.&#x000D;&#x000A;System.Reflection.ReflectionTypeLoadException: Mindestens ein Typ in der Assembly kann nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie weitere Informationen ben&#x00F6;tigen.&#x000D;&#x000A;   bei System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)&#x000D;&#x000A;   bei System.Reflection.RuntimeAssembly.get_DefinedTypes()&#x000D;&#x000A;   bei TomsToolbox.Composition.MetadataReader.Read(Assembly assembly) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:Zeile 27.&#x000D;&#x000A;   bei System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   bei TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:Zeile 44.&#x000D;&#x000A;   bei ResXManager.VSIX.VsPackage.FillCatalog() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:Zeile 201.&#x000D;&#x000A;   bei System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   bei System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   bei ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__15.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:Zeile 102.&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- Ende der Stapel&#x00FC;berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel&#x00F6;st wurde ---&#x000D;&#x000A;   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass68_1.&lt;InternalGetResult&gt;b__1()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass68_0.&lt;InternalGetResult&gt;b__0()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass76_0.&lt;InvokeWithWaitDialog&gt;b__0()&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)&#x000D;&#x000A;   bei Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

It is not possible to start ResXResourceManager. After reinstallation, it is working till next restart of VS.

**Comment by tom-englert** [comment]
Did you try all this: https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md?

**Comment by DavidStania** [comment]
Hi tom,
I did some recommended solutions but this error still exists. But today, maybe after restarting the machine, this error disapears. 
Best regards.
