### ISSUE TITLE
Import excel file not working in standalone app

### ISSUE THREAD

**Issue by rachelyeshurun** [dotnet/ResXResourceManager#478]
**Describe the bug**
I have been using ResXResourceManager add-on in Visual Studio for a few months.
Works great, I even sent in a little donation!
Now I wanted to onboard the product manager, so I exported to excel spreadsheet from within VS and tried to import the spreadsheet to the standalone version.
But didn't see anything.
The standalone version does show the keys and values for all the languages if I set the directory to my language resources.
But the product manager doesn't have that setup. They only have the standalone application and the excel spreadsheet.
How does one import an excel spreadsheet to the standalone app? Is there some missing documentation or a bug?

**To Reproduce**
Downloaded standalone version
![image](https://user-images.githubusercontent.com/1388016/169688139-76f4d3c0-917f-4f11-a856-8075c09fc492.png)

Exported file
[2022_05_22_12_17.xlsx](https://github.com/dotnet/ResXResourceManager/files/8749147/2022_05_22_12_17.xlsx)

Clicked on Import in standalone app, chose above file
![image](https://user-images.githubusercontent.com/1388016/169689109-ba70460e-d3b5-43e6-8636-131931ff7cb3.png)

I tried adding in all the languages that I have in the excel file and then Import.. but the result was the same.
![image](https://user-images.githubusercontent.com/1388016/169689249-d2e3e5fe-36b8-4eeb-a936-94f738c09184.png)

**Expected behavior**
After import, I expect to see all the keys and values for all the language columns in the excel spreadsheet and resource files generated for each language.

**Comment by tom-englert** [comment]
You can only import changes done to an Excel file into an existing solution, not spin up a new solution with all projects from scratch from an Excel.
If your product manager has ResXManager, just send him your sources, not the Excel.
