### ISSUE TITLE
Scripting module - A .saproj/.csproj conflict.

### ISSUE THREAD

**Issue by jovanmatic** [dotnet/ResXResourceManager#485]
Hi!

We think we found strange behavior in your Scripting module.

In our solution, there are several projects in which the name of the .saproj file is alphabetically in front of the name of the .csproj file (for example, **project.saproj** and **ProjectInformation.csproj**). All other projects in the solution have a vice versa situation and they are fine.

![1](https://user-images.githubusercontent.com/17766023/172858587-7a5aa682-b371-475a-bb0b-d1c4a420e6f5.jpg)

When we export all resources and translations in an Excel file using the Scripting module, we're getting the '**project**' value for the problematic projects in the first column (a Project column) instead of the '**ProjectInformation**'.

![2](https://user-images.githubusercontent.com/17766023/172861813-91f6efb7-f0d3-4aa6-9fa7-d5ab02e4af13.jpg)

For testing purposes, we deleted the .saproj file from all of those projects. Please note that these .saproj files are required and their deletion can't be the final solution. They help us to use the Smart Assembly program for post-processing. Under these conditions, we exported the Excel file using the Scripting module and we got the valid values in the first column (a Project column), for all of the problematic projects.

![3](https://user-images.githubusercontent.com/17766023/172862207-66611434-a3a5-4124-8e51-9d7c9a5a2c2c.jpg)

**We want to perform an automatization of the solution's localization process.
For that reason, the Scripting module is very important to us.**

Does the described behavior sound familiar to you?
What is the logic for retrieving the appropriate *.*proj file?

Thank you for your answer in advance.

**Comment by tom-englert** [comment]
I don't think ResXManager can do anything here. Just use the recommended naming scheme or better use another extension than .saproj
