### ISSUE TITLE
Is it possible to add the ability to group entries in a Resx file

### ISSUE THREAD

**Issue by MisakaCirno** [dotnet/ResXResourceManager#488]
I have a project with many windows, and each window has a lot of content that needs to be translated.
When I need to modify the windows, the content that needs to be translated will change as well, but all the translated content needs to be stored in a Resx file, and it is rather overwhelming to manage the translated content in each window.
Therefore, is it possible to add a grouping function for each Resx file? So that I can manage different windows separately. Or is there any way I don't know but better to face this situation?

**Comment by tom-englert** [comment]
![ResXManager_JQsgLewL6z](https://user-images.githubusercontent.com/10229954/175770435-e1060fa9-9884-452a-aff3-319121903d91.gif)

**Comment by MisakaCirno** [comment]
> ![ResXManager_JQsgLewL6z](https://user-images.githubusercontent.com/10229954/175770435-e1060fa9-9884-452a-aff3-319121903d91.gif) [ ](https://user-images.githubusercontent.com/10229954/175770435-e1060fa9-9884-452a-aff3-319121903d91.gif) ![ResXManager_JQsgLewL6z](https://user-images.githubusercontent.com/10229954/175770435-e1060fa9-9884-452a-aff3-319121903d91.gif) [ ](https://user-images.githubusercontent.com/10229954/175770435-e1060fa9-9884-452a-aff3-319121903d91.gif)

Thank you for your reply, but maybe I didn't describe my problem clearly.
I was hoping for grouping within a single file, not for multiple files.
In the image you provided, for example, "ResXManager.Model" and "ResXManager.Translators" should be two different files.
For example, like in the image:
![图片](https://user-images.githubusercontent.com/14026438/177038703-63651039-c519-4991-8830-31a7382c140e.png)
Is it possible to do this? Or is splitting into different files the best practice?

**Comment by tom-englert** [comment]
Yes, splitting into different files is the best solution - else how cold RXRM guess by which criteria you want to group entries of a single file?

**Comment by MisakaCirno** [comment]
> Yes, splitting into different files is the best solution - else how cold RXRM guess by which criteria you want to group entries of a single file?

What I am doing is storing different items into different sheets of an excel file. Finally merge all the forms together and then use the import excel file function to bring these things into the RXRM, maybe RXRM could be used in a similar way. But obviously this would require storing all the content additionally, which sounds like a lot of work.
Thanks for your reply, I might try to use json file instead of excel files and then make a tool to manage json files and export excel files.
