### ISSUE TITLE
Code generator does not work in shared projects

### ISSUE THREAD

**Issue by FJGR65** [dotnet/ResXResourceManager#489]
Yes, you will tell me that it does not work in Visual Studio either.

However, I don't think it would be too much work to call the corresponding extension, or create a method that can generate the code. I don't think it's too difficult.

**Comment by tom-englert** [comment]
No clue what you are talking about

**Comment by FJGR65** [comment]
[ConsoleApp1.zip](https://github.com/dotnet/ResXResourceManager/files/9158542/ConsoleApp1.zip)


This is an example.

As you can see, I have modified the resource files, but the generated code remains unchanged.

It is built with VS 2022, but it happens with any version.

**Comment by tom-englert** [comment]
If you don't think it's difficult, you can provide a PR.

**Comment by FJGR65** [comment]
[ConsoleApp1.zip](https://github.com/dotnet/ResXResourceManager/files/9161753/ConsoleApp1.zip)


Well, it is no longer necessary.

I send the previous example modified and working.

I've gotten it to work.
The credit is not mine, thanks to this article:

[https://stackoverflow.com/questions/4197029/how-to-have-different-solutions-refer-to-one-resx-file](url)
