### ISSUE TITLE
Microsoft Terminology does not work

### ISSUE THREAD

**Issue by abubakrtaha** [dotnet/ResXResourceManager#502]
**Describe the bug**
Translate using Microsoft Terminology does not work

**Error**
MS Terminology: There was no endpoint listening at http://api.terminology.microsoft.com/Terminology.svc that could accept the message. This is caused by an incorrect address or SOAP action. The remote server returned an error: (404)  Not Found

**Findings**
Current URL used by ResXResourceManager is http://api.terminology.microsoft.com/Terminology.svc
I believe the fix is just changing http to https so the URL becomes https://api.terminology.microsoft.com/Terminology.svc

**Comment by tom-englert** [comment]
@PCAssistSoftware Looks like this service is gone. I no one can provide an updated url, I will remove this translator in the next release.
