### ISSUE TITLE
Add setting for indentation (how many spaces per level)

### ISSUE THREAD

**Issue by alex3683** [dotnet/ResXResourceManager#506]
**Is your feature request related to a problem? Please describe.**

Our resx files are indented by 4 spaces on each level. When I add a key and save, the new XML node is indented by 2 spaces per level and all exisitng opening `data`-Tags are being reformatted to also have an indentation level of 2, while everyhing else stays at 4. That is frustrating 😔

**Describe the solution you'd like**

First, indentation should be applied consistently throughout the complete file (this would rather be a bug report than a feature request). Second, it would be nice to keep the 4 spaces, since I don't want to have file changes everytime I save an existing file.

**Describe alternatives you've considered**

I use the Localization Manager of Rider since we switched from Visual Studio to Rider, but I really like ResX Resource Manager a lot more. However this is something keeping me from using it right now :-/

**Additional context**

I'm using the standalone version 1.69.5408.0

A small extract of what the diff looks like:
![grafik](https://user-images.githubusercontent.com/768322/200275009-72c885ec-ac2f-48b9-b238-e620e27a40c1.png)

**Comment by tom-englert** [comment]
The VS built in resx editor also has a hard coded 2-space indent, so that's been the standard for decades now.
Since deviating from the standard always causes pain, I would strongly recommend using the standard 2 spaces indent.

**Comment by alex3683** [comment]
I can totally understand your point and why you wouldn't want to change a thing. It's always a pain switching dev environments with their own strong opinion on code style.

Thanks for your hint on the default styling of Visual Studio. I just checked on my resx files and it seems that somehow an inconsistent styling got in and Rider just tried to apply that everywhere. So I guess you can close this issue if you don't want to make this configurable.
