### ISSUE TITLE
Show most recent or favorite folder selector in standalone version

### ISSUE THREAD

**Issue by alex3683** [dotnet/ResXResourceManager#507]
**Is your feature request related to a problem? Please describe.**

I have to switch between multiple cloned versions of our product (e.g. one for feature implemenation and one for bugfixing). Currently I always have to pick the respective folder via the folder picker every time I have to work in one of these versions.

**Describe the solution you'd like**

It would be nice if there was a list of most recently used locations or manually added favorites to make switching between folders simpler and quicker.

**Describe alternatives you've considered**

none

**Additional context**

I'm using the standalone version 1.69.5408.0

Here I'd like to have the most recent / favorite locations list:
![grafik](https://user-images.githubusercontent.com/768322/200276428-4a5dca30-b2b8-4ea7-a820-58343a863e9c.png)

**Comment by etherfield** [comment]
I'll do it.

**Comment by alex3683** [comment]
Thanks for the quick implementation!
