### ISSUE TITLE
Keys from resources not added 

### ISSUE THREAD

**Issue by marcoahp** [dotnet/ResXResourceManager#509]
I use ResX Manager perfectly in a solution. Thanks for you effort, it is great. But when I try tu use in other solutions, I open ResX Manager and the resources are listed, but without any key. What I'm doing wrong?
I send you the image of working ok project and failing project.
This is ok:
![ResX_ok](https://user-images.githubusercontent.com/49716815/202709959-6ed746c9-70d9-4a26-9525-ad8cd8c078a6.jpg)
This is failing
![ResX_fail](https://user-images.githubusercontent.com/49716815/202709963-0f8f6076-0ed1-4caa-b102-e66135523a07.jpg)

This is my output:
ResX Resource Manager loaded.
Home: https://github.com/dotnet/ResXResourceManager
Report issues: https://github.com/dotnet/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: c:\users\marco\appdata\local\microsoft\visualstudio\16.0_b1dbf80d\extensions\l2t302dl.2wd
Version: 1.70.5426.0
.NET Framework Version: 528372 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=False (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)

Thanks

**Comment by tom-englert** [comment]
In the second image all projects start with a backslash.
However since there is no error reported in the log, I can't tell much without seeing the whole solution.

**Comment by marcoahp** [comment]
> In the second image all projects start with a backslash. However since there is no error reported in the log, I can't tell much without seeing the whole solution.

Yes, this is because the code files are in the same folder I think. I've created a new project with a form and a button. Then I open ResX manager, and the caption of the button do not appear in the key list of the form.
Am I missing something? Could you test this to se if it works for you?

**Comment by tom-englert** [comment]
Did you set the form to localizable?

**Comment by marcoahp** [comment]
Omg, I forgot it. Thanks

 

De: tom-englert ***@***.***> 
Enviado el: viernes, 18 de noviembre de 2022 18:53
Para: dotnet/ResXResourceManager ***@***.***>
CC: marcoahp ***@***.***>; Author ***@***.***>
Asunto: Re: [dotnet/ResXResourceManager] Keys from resources not added (Issue #509)

 

Did you set the form to localizable?
