### ISSUE TITLE
ResXManager won't start after latest update

### ISSUE THREAD

**Issue by MichaelHeimann1980** [dotnet/ResXResourceManager#511]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
ResXManager won't start after latest update. An error message appears (see attachment)
![Screenshot 2022-11-28 094629](https://user-images.githubusercontent.com/94376340/204234385-0b942046-8b65-455b-9ac9-c2887371b0d5.png)
linking to the aktivity log.

in the xml file:
 <entry>
    <record>1060</record>
    <time>2022/11/28 08:43:54.144</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Die Datei oder Assembly &quot;System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Die Datei oder Assembly &quot;System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)&#x000D;&#x000A;   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)&#x000D;&#x000A;   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeType target)&#x000D;&#x000A;   at System.RuntimeType.GetCustomAttributesData()&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.ReadType(TypeInfo typeInfo, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 42&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.ReadTypes(IEnumerable`1 typeInfos, IList`1 result) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 34&#x000D;&#x000A;   at TomsToolbox.Composition.MetadataReader.Read(Assembly assembly) in D:\a\1\s\src\TomsToolbox.Composition\MetadataReader.cs:line 25&#x000D;&#x000A;   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 41&#x000D;&#x000A;   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 assemblies) in D:\a\1\s\src\TomsToolbox.Composition.Ninject\ExtensionMethods.cs:line 31&#x000D;&#x000A;   at ResXManager.VSIX.VsPackage.FillCatalog() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 194&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__15.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 102&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A</description>
    <guid>{43B35FE0-1F30-48DE-887A-68256474202A}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**To Reproduce**
Steps to reproduce the behavior: Start ResXManager in visual studio 2019

**Expected behavior**
Should start normally.

**Comment by tom-englert** [comment]
Can s.o. with VS2019 test if the latest build at https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a fixes this?

**Comment by exuser** [comment]
How can i downgrade please?

**Comment by Twoleeland** [comment]
> Can s.o. with VS2019 test if the latest build at https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a fixes this?

--> Downloaded it, tested in VS2019, no VSPackage error and RESX-Manager works again! Thx for fast fix!!! 🙌🙌🙌👌👍😁😉

**Comment by jackmcbrezel** [comment]
> Can s.o. with VS2019 test if the latest build at https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a fixes this?

yup - works fine after the manual installation of the vsix package!

Thanks 👍
