### ISSUE TITLE
Delay before build is started

### ISSUE THREAD

**Issue by tomastysercz** [dotnet/ResXResourceManager#520]
Hi, i installed your ResXResourcesManager, 
But after restart VS i have from 5 to 10 seconds delay build. 
I press the build button, then VS making "nothing" and after 5 seconds is build started (the output window start list)
Whe is the ResXResourcesManager disabled, the build is quickly.
We have a large c# solution more then 220 projects with 10000 "cs" files and more that 8200 resx files

**Comment by tom-englert** [comment]
Did you try switch off error reporting?
![image](https://user-images.githubusercontent.com/10229954/214842934-6eb365ca-0c62-466a-9962-451cd23ae988.png)

**Comment by tomastysercz** [comment]
Where is this settings ?

**Comment by tomastysercz** [comment]
super, now it isn't delayed.
We have warnings disabled...
Thank you
