### ISSUE TITLE
Double quotes is not encoded to &quot;

### ISSUE THREAD

**Issue by kinguru** [dotnet/ResXResourceManager#521]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
Seems some characters must be presented as XML encoded, like " => &quot;

**To Reproduce**
Make a translation with characters: " > '  < &

**Expected behavior**
Characters must be necoded: " ' > < &

**Comment by tom-englert** [comment]
Can you please provide a comprehensive description on how to reproduce this?
What do you mean by "Make a translation"?

**Comment by kinguru** [comment]
Please add a resource via visual studio extension with value contains any of the mentioned characters.

Save, build the project.

Open resource file with notepad and check value in the file. Seems value is not encoded well - specified characters are not encoded.

**Comment by tom-englert** [comment]
I can't reproduce. If that was true, it would be a bug in [System.Xml.Linq](https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq), which is very unlikely.

**Comment by tom-englert** [comment]
It's exactly like it should be:
![image](https://user-images.githubusercontent.com/10229954/213865659-53a92931-4ade-40a5-88d1-595d3e65f43d.png)

![image](https://user-images.githubusercontent.com/10229954/213865646-e06b116e-6ae1-4f0b-878e-b481e040fdac.png)

**Comment by kinguru** [comment]
Is it possible to add an option to save XML with or without encoding? Having a trouble with 3rd party tool integration. Seems both approaches are correct (with and without encoding). But it's a big problem when one tool use encoding and another is not. In case you have 1000 translations much of it has quotes and false-positive changes appear during commit changes review.

With best regards,
Ilya

**Comment by tom-englert** [comment]
You can fork the project and replace the XML writing to match your needs.
