### ISSUE TITLE
Set the language for autogenerated comments "Looks up a localized string similar to"

### ISSUE THREAD

**Issue by darioinova** [dotnet/ResXResourceManager#524]
### Discussed in https://github.com/dotnet/ResXResourceManager/discussions/523

Hi there,
     the only annoying issue in this amazing extension deals with the autogenerated comments.

**_Is there any way to force the comments to be always in, let say, English?_**

We are working in a team with different OS language setup.
Adding a translation generates comments in English or in Italian. 
```
        /// <summary>
        ///   Cerca una stringa localizzata simile a STRING.
        /// </summary>
```
vs
```
        /// <summary>
        ///   Looks up a localized string similar to STRING.
        /// </summary>
```

The mess is keeping track using Git ... every line is a change.
We've missed a lot of merge neglecting the changes.

Or, is there any better way to manage this issue?

thanks a lot!!!

**Comment by tom-englert** [comment]
This is done by the built in VS code generator. 
You can use this instead:
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Custom-Code-Generator.md
