### ISSUE TITLE
Method not found 'Void EnvDTE._dispTaskListEvents_TaskNavigatedEventHandler..ctor(System.Object, UIntPtr)

### ISSUE THREAD

**Issue by caryomaha** [dotnet/ResXResourceManager#527]
after migrating from VS 2019 to VS 2022 community version, my XtraReport designer.cs is not loading . getting the following error.

Method not found: 'Void EnvDTE.\_dispTaskListEvents\_TaskNavigatedEventHandler..ctor(System.Object, UIntPtr)'

Here is the callstack screenshot

![image](https://user-images.githubusercontent.com/90724282/216190948-c0c74e41-da92-41a0-96b9-78e59dba1979.png)

PLEASE HELP,.Its URGENT  as ll my Xtrareports designer.cs are not opening

**Comment by tom-englert** [comment]
What makes you think this is related to ResXResourceManager?

**Comment by caryomaha** [comment]
Yes, you are correct. It's Devexpress version compatibility related. DevExpress addressed it and issue is resolved now.

Thanks a bunch for your prompt response and lead.
