### ISSUE TITLE
Red cells despite translation

### ISSUE THREAD

**Issue by El-Pazzo** [dotnet/ResXResourceManager#529]
Hi,

I got several languages I translated according to official grammar and standards, some cells thus contain non-breaking spaces (&nbsp;) for specific languages where the other languages don't need these non-breaking spaces. Some language cells (not all) containing these are showing red although correctly translated. This seems to be the case for some other html encapsulated characters (&eacute;, &egrave;).

Other strings are translated without such characters but every language except neutral are highlighted red:

e.g.
Mrs. -> Frau -> Madame -> Signora -> Madamm -> Mevrouw -> Señora

but there also strings that have same punctuation and everything and still flag errors although there are no errors.

Best regards,
Pascal

**Comment by tom-englert** [comment]
Spell checker: This is the system built in DotNet spell checker. There is nothing we can do to change it's behavior.
Punctuation: You can suppress false positives by right-click and selecting consistency checks from the context menu.

**Comment by El-Pazzo** [comment]
Could you at least insert an option to activate/deactivate (checkbox) spellchecking and other checks for the whole file?

**Comment by tom-englert** [comment]
You can disable punctuation checks on the configuration tab

**Comment by El-Pazzo** [comment]
well it was not only punctuation check. I disabled all checks and finally got a normal view.
