### ISSUE TITLE
A previous session ended unexpectedly  Disabling the extension ResxManager 1.74.552.0

### ISSUE THREAD

**Issue by mjjalala** [dotnet/ResXResourceManager#533]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by tom-englert** [comment]
Did you read the issue template?
