### ISSUE TITLE
Config for Disable Warnings for missing Neutral Language

### ISSUE THREAD

**Issue by garcipat** [dotnet/ResXResourceManager#536]
We have the resx files generated and we don't use a neutral language file. The extension dsplays a Warning without Code. So we cannot supress the warning even if we want to and there is no option to disable displaying the warnings.

**Describe the solution you'd like**
Add an option to deactivate it.

**Describe alternatives you've considered**
Add a code to the warning to be able to suppress it.

**Additional context**
![image](https://user-images.githubusercontent.com/7288563/221541605-03ebe654-0dba-456e-b41b-4dc476a97720.png)

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/221555235-c762ab5f-9173-4e80-a045-b484a99e78cd.png)
