### ISSUE TITLE
Killed my VS2022 Enterprise instance, have to do a repair now

### ISSUE THREAD

**Issue by Legends** [dotnet/ResXResourceManager#538]
Installed the extension, which a hang for quiet a longer time in the initialization phase, then it says successfully installed.
Host: Win 10 Pro x64 (Intel Core I7), VS 2022 Enterprise.

VS won't even start in /safemode. 

> Log Name:      Application
> Source:        .NET Runtime
> Date:          02.03.2023 14:12:32
> Event ID:      1026
> Task Category: None
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      MyComputer
> Description:
> Application: VSIXInstaller.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IndexOutOfRangeException
>    at System.Buffer.InternalBlockCopy(System.Array, Int32, System.Array, Int32, Int32)
>    at System.IO.StreamWriter.Write(Char[], Int32, Int32)
>    at System.IO.TextWriter.WriteLine(System.String)
>    at VSIXInstaller.Logger.WriteLine(System.String)
>    at VSIXInstaller.App.App_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
>    at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
>    at System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
>    at System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at System.Windows.Application.Run(System.Windows.Window)
>    at VSIXInstaller.App.Main()
> 
> 
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Version>0</Version>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Opcode>0</Opcode>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2023-03-02T13:12:32.1225250Z" />
>     <EventRecordID>28914</EventRecordID>
>     <Correlation />
>     <Execution ProcessID="0" ThreadID="0" />
>     <Channel>Application</Channel>
>     <Computer>MyComputer</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Application: VSIXInstaller.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IndexOutOfRangeException
>    at System.Buffer.InternalBlockCopy(System.Array, Int32, System.Array, Int32, Int32)
>    at System.IO.StreamWriter.Write(Char[], Int32, Int32)
>    at System.IO.TextWriter.WriteLine(System.String)
>    at VSIXInstaller.Logger.WriteLine(System.String)
>    at VSIXInstaller.App.App_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
>    at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
>    at System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
>    at System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at System.Windows.Application.Run(System.Windows.Window)
>    at VSIXInstaller.App.Main()
> 
> </Data>
>   </EventData>
> </Event>

**Comment by tom-englert** [comment]
As you can see from the attached stack trace this is a crash in the Visual Studio VSIX installer, not in RXRM.

**Comment by Legends** [comment]
ok, I will. Thanks.
