### ISSUE TITLE
Fontsize very small

### ISSUE THREAD

**Issue by AndreasDecke** [dotnet/ResXResourceManager#541]
Hello,

First of all thanks for the good tool. My monitors work with UHD resolution. Unfortunately, the icons and the font in the manager are very small! How can I get a larger font. Is there a config?

Thanks very much

**Comment by tom-englert** [comment]
Ctrl+MouseWheel

**Comment by AndreasDecke** [comment]
👍👍👍
Thanks

**Comment by tom-englert** [comment]
Or change the font size of the VS editor
