### ISSUE TITLE
Exclude shor strings from translation

### ISSUE THREAD

**Issue by Praetorian11** [dotnet/ResXResourceManager#543]
**Is your feature request related to a problem? Please describe.**
In translation there is a lot such strings ('%', "[h]", ...)

**Describe the solution you'd like**
Add number parameter "Exclude strings shorter than {N} from translation"

**Comment by tom-englert** [comment]
You can filter by e.g. `^.{0,n}$` and mark all as invariant

**Comment by tom-englert** [comment]
@Praetorian11 did this work for you, or do you plan to submit a PR with a different solution?

**Comment by tom-englert** [comment]
No reply, closed as stale
