### ISSUE TITLE
Snaphot files different between standalone and script version

### ISSUE THREAD

**Issue by timatbuild** [dotnet/ResXResourceManager#547]
**Describe the bug**
When you create a snapshot using the standalone version, in its' UniqueName member, it will contain the relative path inside its' project.
When you create a snapshot of the same source folder using the scriping version, in its' UniqueName member, it will contain only the resource file name, it will not include the relative path when applicable.

**To Reproduce**
see description

**Expected behavior**
Shouldn't the standalone and scripting version produce compatible snaphot files, as they are base on the same engine?

Best regards,
Tim

**Comment by timatbuild** [comment]
Dear,

It seems that in the latest versions, **now also in the Excel exports**, the relative paths of the resources files within their projects got included too, while they were previously NOT included, which renders **all translation Excel files that we have already sent to external translators unusable**, as their keys suddenly change for most of >1700 resources files ! So I'll have to use the older version to import those...

While this looks correct, it is a major change for us and possibly multiple users as the resource file name field is different now in the Exels and snapshots!

**Comment by tom-englert** [comment]
@timatbuild sorry for the inconveniences,😔
