### ISSUE TITLE
Support OpenAI translator

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/ResXResourceManager#549]
I needed better translation support than the default Azure translator for a project, so I did a quick hack to try using OpenAI (GPT) translation instead. It turned out to work really well, so I wrapped it up in a PR here: https://github.com/dotnet/ResXResourceManager/pull/548

Feel free to use it. I'd be happy to clean it up if necessary to follow this projects guidelines, just let me know.

**Comment by joakimriedel** [comment]
@tom-englert , some quick notes after extensive testing during this week;

- the `gpt-3.5-turbo` model should be recommended to users, after translating thousands of resource strings from a mix of Nordic languages to European languages it's clearly more capable than `text-davinci-003`. But both models work in my updated PR, in case users prefer/only have access to either one.
- I found it valuable (if necessary) to add a custom prompt of "Use the formal you form when translating" (or similar) so that the translator would use German "Sie" or French "vous" instead of mixing with "Du"/"tu" - unless that is intentional of course.
- I have some issues where OpenAI would flag certain translations "inappropriate" and return the "content_filter" error code. It would be great if there were some way to provide an error code or similar per row in the translations view so that the user can see which translations that triggered error(s). Right now, if I'm understanding it correctly, it is just possible to write a single string to the output window with the latest error code.
- using the OpenAI models to translate from more than one language of high quality as source is a game changer for us, I hope other users of ResXResourceManager will appreciate it as well!

**Comment by tom-englert** [comment]
Unfortunately I had to disable this cool feature, because it crashed the VSIX - in the context of Visual Studio it can't load Azure.AI.OpenAI.dll, see https://developercommunity.visualstudio.com/t/Visual-Studio-extension-fails-to-load-wh/10388708

**Comment by joakimriedel** [comment]
Oh that's unfortunate. The OpenAI package is just a thin wrapper, I could easily rewrite it to use HttpClient during next week.

**Comment by tom-englert** [comment]
That would be cool!

**Comment by joakimriedel** [comment]
Done. See https://github.com/dotnet/ResXResourceManager/pull/563

**Comment by joakimriedel** [comment]
@tom-englert this looks merged with 1.76 commit, but no 1.76 release yet?

**Comment by tom-englert** [comment]
Will have time for a release probably next week

**Comment by tom-englert** [comment]
@joakimriedel 1.76 is now deployed. I'd like to request some amplification for this feature, but realized that there is no documentation yet except the descriptions here and in the PR. 

Maybe you can add a few words to https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Automatic-Translations.md to briefly describe about the models supported?

**Comment by joakimriedel** [comment]
I am a bit offline atm due to vacation, will make a PR with doc update as
soon I have tested the new model from OpenAI that will replace the now
deprecated text-davinci-003 model.

Den fre 7 juli 2023 15:54tom-englert ***@***.***> skrev:
