### ISSUE TITLE
Flag for Frisian language

### ISSUE THREAD

**Issue by ftamminga** [dotnet/ResXResourceManager#555]
I would like to add a separate flag for the Frisian language. It is an official minority language, spoken in the Netherlands and has the culture code fy-NL. The problem in ResXManager.View.CultureToImageSourceConverter.cs is that the 'NL' part of the culture now is the key for the flag to return, and that is the dutch flag. But I need it to be the Frisian flag. [https://en.wikipedia.org/wiki/Flag_of_Friesland](url)

Shall I make a exception in the code just for Frisian? I can't imagine the Frisian is the only minority language that has its own flag this way.

**Comment by tom-englert** [comment]
NL is the fallback because fy does not exist:
https://github.com/dotnet/ResXResourceManager/blob/master/src/ResXManager.View/Converters/CultureToImageSourceConverter.cs.
So if you add the fy flag, it should work

**Comment by tom-englert** [comment]
If it's reverse, add it to the   `NeutralCultureCountryOverrides`

**Comment by ftamminga** [comment]
I can't get it to work.
I added a fy.gif to the Flags folder, added "fy" to the _existingFlags in CultureToImageSourceConverter.cs
Both "fy" and "fy-NL" should show the Frisian flag.

But somehow I still get the Dutch flag.

I tried the DefaultOverrides in NeutralCultureCountryOverrides.cs with two variations:
A) private const string DefaultOverrides = "en=en-US,zh=zh-CN,zh-CHT=zh-CN,zh-HANT=zh-CN,fy-NL=fy,";
and 
B) private const string DefaultOverrides = "en=en-US,zh=zh-CN,zh-CHT=zh-CN,zh-HANT=zh-CN,fy=fy-NL,";

It does not help. In both cases, in CultureToImageSourceConverter.cs at line 63,  countryOverride is set to "fy-NL".
And since the NL part is used for the flag, I only get the dutch flag.
How can I solve this?

Any ideas?

**Comment by tom-englert** [comment]
Sorry, but this is such a rare use case, I can't spend time on this. 
Maybe just hard code the exception and build your private version that has the flag.

**Comment by etherfield** [comment]
I've added support for flag icons that match culture name exactly (e.g. fy-nl.gif, en-us.gif etc.)
I believe custom icons for languages will improve usability, especially if there are multiple languages spoken within one country.
@tom-englert please take a look #592

Right now there is a gif for fy-NL only but I think it would be nice to address other icons in future issues. For example, Valencian language has no icon at all.
![VA](https://github.com/dotnet/ResXResourceManager/assets/148793545/b9baeb5c-421a-495a-8f79-ebd2c064e12c)
