### ISSUE TITLE
how restart translation from scratch again

### ISSUE THREAD

**Issue by ltemimi** [dotnet/ResXResourceManager#558]
hi 

I have errors in my translations and would like to start over again. Resx seems to only translate new keys (which makes sense) in my use case I need to start over.

or is there a way of re-translating only the translations with errors i.e colored in pink

Please help

**Comment by tom-englert** [comment]
I guess you are talking about automatic translations. 
It will translate all empty entries, so just clear the ones you want to redo.

**Comment by ltemimi** [comment]
Thanks
