### ISSUE TITLE
Filter is cleared (but not un-applied) when switching branches

### ISSUE THREAD

**Issue by JasonTBS** [dotnet/ResXResourceManager#559]
When using a filter to limit results of keys or values and switching selected branch the filter text is cleared however the applied filter remains and it is necessary to click to filter again and re-enter the value or apply the empty filter to display the correct results.

**Comment by tom-englert** [comment]
How can I switch a branch in RXRM?

**Comment by JasonTBS** [comment]
Sorry, should have been a little more specific. This was tested when using Git branches and the change of the selected branch is done in the VS interface either using the Manage Branches window or the branch selector at the bottom right of the VS window.

**Comment by tom-englert** [comment]
It works fine when I change resx files with an external editor, might be dependent on what other files are changed, e. g. Project or solution.
Did you try to click the refresh button in RXRM?

**Comment by tom-englert** [comment]
@JasonTBS any additional information what needs to change to get the effect you described?

**Comment by JasonTBS** [comment]
Although unable to reproduce the issue simply by switching branches I am able to produce the effect by doing the following:

1. Open folder path to code
2. Open resx file in default editor
3. Open RXRM window and select resource file
4. Apply filter to Neutral value
5. Close RXRM window
6. Open solution within that code path
7. Open RXRM window

The filter remains applied filtering the displayed records however the filter text is gone. Clicking refresh in RXRM does nothing (does not reset the filter to empty). To undo the filter, a new filter must be set and cleared.

I have discovered a similar issue I will try to describe, when either a solution or a folder path is open and a branch is selected that has additional (newer) resource keys to another branch. Applying a filter in RXRM and then switching to the older branch the resource key records are updated to reflect the older branch not having all the keys. When switching back to the new branch with the new keys (that are part of the filter) the set of keys does not update to show the new key(s). Clicking refresh does not fix it. Re-applying the filter value by backspacing and re-typing a single character does fix it and show the expected key record.
