### ISSUE TITLE
Xliff file not working

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/ResXResourceManager#572]
Im transitioning over from 'Microsoft multilingual toolkit'. I've installed extension and enabled xliff sync -
![image](https://github.com/dotnet/ResXResourceManager/assets/6544051/59cb3bda-19a6-4a9a-9ca2-3d98fdb03806)
But changing the default resx wasnt updating the existing xliff file. So i deleted the existing one expecting this extention to generate the xliff file, but it hasnt.
_(did a clean rebuild/ restart)_

Can see its updated the solution - 
![image](https://github.com/dotnet/ResXResourceManager/assets/6544051/f80d897f-43c5-4dac-97ce-77d2751a96b3)

**Comment by tom-englert** [comment]
Hard to see from a screenshot, Can you post a sample solution?

**Comment by IeuanWalker** [comment]
@tom-englert It's a .net maui project, the resx is located in the 'Resources>Languages' folder
[MultilingualRepo.zip](https://github.com/dotnet/ResXResourceManager/files/12147168/MultilingualRepo.zip)

**Comment by tom-englert** [comment]
There is no xlif in the project, so that can't work, xlif files are only synchronized, not created.

**Comment by IeuanWalker** [comment]
@tom-englert Does the xliff file need to be in the same folder as the resx files? And what's the naming convention to link them up to the right resx file?

In my actual project there was an exsisting xliff file in its own folder but wasnt syncing too it

**Comment by tom-englert** [comment]
As far as I remember the .xlif contains a reference to the .resx. 
I used this repo as reference: https://github.com/WildGums/Orchestra

**Comment by IeuanWalker** [comment]
@tom-englert mmm ye, my original xliff file has that - 
![image](https://github.com/dotnet/ResXResourceManager/assets/6544051/b479cc53-21c1-4397-8a8e-e1918b039e05)

Will try again in this test repo i created

**Comment by IeuanWalker** [comment]
@tom-englert i've tried multiple things nothing seams to work. Here is the updated repo with the xliff file - 
[Repo.zip](https://github.com/dotnet/ResXResourceManager/files/12163446/Repo.zip)

The xlf file looks standard and correct - 
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-GB" target-language="cy" original="MultilingualTest/Resources/Languages/AppResources.resx" tool-id="MultilingualAppToolkit" product-name="n/a" product-version="n/a" build-num="n/a">
    <header>
      <tool tool-id="MultilingualAppToolkit" tool-name="Multilingual App Toolkit" tool-version="4.0.6900.0" tool-company="Microsoft" />
    </header>
    <body>
      <group id="MultilingualTest/Resources/Languages/AppResources.resx" datatype="resx">
      </group>
    </body>
  </file>
</xliff>
```

This is the folder structure - 
![image](https://github.com/dotnet/ResXResourceManager/assets/6544051/1111bda4-9d8f-4077-ab8f-e0fb1f9245d5)
And i've tried moving the xlf file to the same folder as the resx, to see if that made any difference _(didn't)_

And there's nothing in the output window that suggest there is an error anywhere

**Comment by IeuanWalker** [comment]
@tom-englert did you mean to close it?

**Comment by tom-englert** [comment]
Now 😏

**Comment by IeuanWalker** [comment]
@tom-englert strange i uninstalled the extension, then reinstalled it.
But it didn't install the latest, still like the first screenshot in my previous comment

**Comment by IeuanWalker** [comment]
All good now, not sure what was going on,
Done a quick test and all looks good.

_fyi, it does auto generate the xlf file if the path isnt correct in the xlf file_

**Comment by tom-englert** [comment]
> fyi, it does auto generate the xlf file if the path isnt correct in the xlf file

😄
