### ISSUE TITLE
Add Google Translate without API Key

### ISSUE THREAD

**Issue by KaiHuaDou** [dotnet/ResXResourceManager#573]
A Google Translate API that does not require an API Key：
v2: `"https://translation.googleapis.com/language/translate/v2?source={from}&target={to}&q={text}`
v1: `"https://translate.googleapis.com/translate_a/single?client=gtx&sl={from}&tl={to}&dt=t&q={text}`

**Comment by tom-englert** [comment]
Can you provide PR?

**Comment by KaiHuaDou** [comment]
See Pull Request #574

**Comment by tom-englert** [comment]
Fixed by #574
