### ISSUE TITLE
Suggestion: This project should be made into a desktop software to implement file project management. In fact, it is very difficult to use and inconvenient as a plug-in.

### ISSUE THREAD

**Issue by AtlantisDe** [dotnet/ResXResourceManager#581]
### Suggestion: This project should be made into a desktop software to implement file project management. In fact, it is very difficult to use and inconvenient as a plug-in.

- **as standalone software**

**Comment by tom-englert** [comment]
RTFM 😏 https://github.com/dotnet/ResXResourceManager#installation

**Comment by AtlantisDe** [comment]
> RTFM 😏 https://github.com/dotnet/ResXResourceManager#installation

Thank you. I will use it.
