### ISSUE TITLE
Adding another language

### ISSUE THREAD

**Issue by guillermochristopher** [dotnet/ResXResourceManager#587]
Hi there,
I am new on this and I am participating on the Hacktoberfest event. Searching I saw this interesting project, which I have been investigating and I decided to participate., but I wouldn't like to do a mess.
I noticed this is the file related to the ResX resources, where there are the pair name-values. The file is only translated to German, is this an exclusive feature or can I add another resource in another language? I am bilingual so, it will not difficult for me.
Second question, can be this file explain in Readme file? Or is it ok?
Thanks

_Originally posted by @guillermochristopher in https://github.com/dotnet/ResXResourceManager/pull/582#discussion_r1370504959_

**Comment by tom-englert** [comment]
I would recommend to read the official Microsoft documentation about the .resx file format and usage.
