### ISSUE TITLE
Trailing Punctuation is too strict `.` -> `。`, `?` -> `;`

### ISSUE THREAD

**Issue by Skgland** [dotnet/ResXResourceManager#589]
**Describe the bug**

Some Languages use different Punctuation e.g. 
`。` instead of `.`
`;` (Greek Question Mark, not a semicolon) instead of `?`
resulting in mismatched trailing punctuation.

**To Reproduce**

Enter an English sentence ending in a `.` or `?` and the corresponding translation in Chinese/Japanese or Greek, respectively.

**Expected behavior**
Translated Punctuation is considered equivalent.

Related #283

**Comment by tom-englert** [comment]
Please extend the mapping and submit a PR:

https://github.com/dotnet/ResXResourceManager/blob/3122c9f3c2847714c45171a7acb2aa9f1d474744/src/ResXManager.Model/ResourceTableEntryRulePunctuation.cs#L41-L64

**Comment by Skgland** [comment]
I wil need to check why `。` was a problem as that appears to be already handled since [650c01d](https://github.com/mkaring/ResXResourceManager/commit/650c01dac3f4773a59729202b64ad56c12acfd81) where this was added in 2019.
