### ISSUE TITLE
Scripting.zip release asset target framework issues

### ISSUE THREAD

**Issue by bdovaz** [dotnet/ResXResourceManager#599]
I want to automate in CI the download of the `Scripting.zip` asset of the latest release.

But I run into the problem that inside there is a folder for each `targetFramework`. This presents 2 problems:
* There is no way to know which folders (= frameworks) are going to be in each release.
* It depends on what you have installed that runtime.

It would be nice that at least in the release the asset does not include those intermediate folders and that it is published only with the most common target and that works without dependencies (portable?).

Thanks

**Comment by tom-englert** [comment]
If you can make it run with just target framework `netstandard2.0`, I'll be happy to integrate it.
