### ISSUE TITLE
Remove Fody and use MVVM Toolkit source generators

### ISSUE THREAD

**Issue by bdovaz** [dotnet/ResXResourceManager#600]
It is the most convenient (only attributes need to be set) and secure (AOT compatible) way to use this pattern today:

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/overview

**Comment by tom-englert** [comment]
INotifyProperyChanged is not the only usage of Fody, so much luck!

**Comment by tom-englert** [comment]
Also the MVVM generator only supports auto-properties, but not with some logic inside (e.g. forwarding)

**Comment by bdovaz** [comment]
Actually, I was taking a look and Fody is used in this project much more than I thought (Fody + other NuGet packages from third parties or yours)... I honestly don't like it because there is too much "magic" that you don't see/understand if you haven't done it yourself and it becomes complicated to contribute to the project.

But well, matter of taste, I close the issue because actually removing the Fody dependencies only for INotifyPropertyChanged, does not solve anything.
