### ISSUE TITLE
"Move to Resource" not replacing string with Code + not adding the value (cshtml - VS Community 2022 64-bit)

### ISSUE THREAD

**Issue by MashhorSoftware** [dotnet/ResXResourceManager#603]
**Describe the bug**
1 - "Move to Resource" not replacing string with Code.
2 - "Move to Resource" not adding the value.

![resxmanagercodebug](https://github.com/dotnet/ResXResourceManager/assets/139355464/1b6074b8-d86d-4430-a03b-88d9913d831c)

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.6
Programing language: cshtml

**To Reproduce**
1 - Right click the string.
2 - Click on "Move to Resource"
3 - Choose any type of Code template.
4 - Type in any value.
5 - Click Ok.

**Expected behavior**
1 - String is replaced with Code.
2 - Value is added to the key values.

**Comment by tom-englert** [comment]
Is there any message in the output window?

**Comment by tom-englert** [comment]
You don't have a neutral resource in your project

**Comment by MashhorSoftware** [comment]
Thank you so much!
it was true, I had to rename my Index.en.resx file to Index.resx, now it's recognized in the plugin as "Neutral" as it was "English [en]" just like in the picture below. it's working perfectly now!
![Screenshot 2023-11-04 160817](https://github.com/dotnet/ResXResourceManager/assets/139355464/f3247e2f-4307-4925-934c-e1304f37703b)
