### ISSUE TITLE
Default value for all languages per key

### ISSUE THREAD

**Issue by etherfield** [dotnet/ResXResourceManager#608]
One of the use-cases I have on a commercial project is to fill out all language cells with a default text when a new key is created. Usually, I would copy-paste the text from Neutral locale to others, but the more languages we support the heavier the burden it becomes. I know falling back to default locale can be implemented instead, but it's just a rule on the project.

I suggest to add 'Default value' input to the 'Add new key' prompt. If simplicity of the interface matters, showing/hiding this field can be made configurable.
I can provide a PR.

![Untitled](https://github.com/dotnet/ResXResourceManager/assets/148793545/eea7f192-0bab-4deb-8277-b9d1d7e1fd05)

**Comment by tom-englert** [comment]
Falling back to the neutral language **is** the default behavior of the `System.Resources.ResourceManager` if there is no value for the current language.

Also when filling out every field, you'll undermine the detection of missing entries, so this request is somewhat contra-dictionary to the current functionality.

If you need to support such anti-patterns, I would recommend to us the scripting module and write a script that populates empty fields.
