### ISSUE TITLE
Error in last version, november 25

### ISSUE THREAD

**Issue by Avtroman** [dotnet/ResXResourceManager#615]
[ActivityLog.zip](https://github.com/dotnet/ResXResourceManager/files/13467125/ActivityLog.zip)
![Снимок экрана (52)](https://github.com/dotnet/ResXResourceManager/assets/42459158/fbcdaded-3cf7-4866-8b5f-2084edb65db1)
![Снимок экрана (53)](https://github.com/dotnet/ResXResourceManager/assets/42459158/6b120854-a8e0-4b8a-8a98-6ec057d87fdf)

**Comment by tom-englert** [comment]
Fixed by a24e1eb7cc4616c8c46f86f7a00724364ca27348
