### ISSUE TITLE
Some punctuation stops translation in Google Lite 

### ISSUE THREAD

**Issue by tkefauver** [dotnet/ResXResourceManager#616]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
Some punction halts translation, I've tested with these `en-US` characters: !.| (exclamation point, period and pipe)

**To Reproduce**
Select Google Lite and attempt to translate `Hey! This is a test` to `zh-CN`

**Expected behavior**
The output should be (according to https://translate.google.com):
 `嘿！ 这是一个测试` 

But the actual output is:
`嘿！`

**Comment by tom-englert** [comment]
Looks like this is a limitation of Google Lite, not RXRM:
![image](https://github.com/dotnet/ResXResourceManager/assets/10229954/451f5d98-e7dd-4988-8d2d-75febdf0dd7e)
We can only show what the provider returns.

**Comment by tkefauver** [comment]
That's lame! Thanks for looking at it though :)

**Comment by tkefauver** [comment]
Hi again, wanted to let you know I found a different Google translate endpoint that doesn't have this flaw! Its mentioned here: https://github.com/ssut/py-googletrans/issues/268.

**Comment by tkefauver** [comment]
@tom-englert Just realized this was closed, I can submit a PR using the updated endpoint. Just let me know!
