### ISSUE TITLE
Line Break in entries

### ISSUE THREAD

**Issue by gchapeaux** [dotnet/ResXResourceManager#619]
**Is your feature request related to a problem? Please describe.**
I had some entries that were only one line long in one language, but when translated needed to be written on several lines.

**Describe the solution you'd like**
The feature is actually already implemented, although I found it randomly, couldn't find any mention of it anywhere. The key is actually *Ctrl+Enter*. It would be nice to be able to use *\n* as well, but not mandatory, I mainly opened this request to have the solution written somewhere.

**Comment by tom-englert** [comment]
Documentation PRs are always welcome

**Comment by tom-englert** [comment]
Fixed by #621
