### ISSUE TITLE
Windows Userform controls are not listed in main Window

### ISSUE THREAD

**Issue by gfue** [dotnet/ResXResourceManager#629]
The main window of ResXManager correctly recognizes the userforms but it does not list the controls.
Do I miss anything to do to get that working (the refresh button does not solve the issue). The Output shows now errors
![image](https://github.com/dotnet/ResXResourceManager/assets/159230107/3f03a363-3ed7-486e-a3b1-4b98eb79361a)
The Forms are not empty.

**Comment by tom-englert** [comment]
Are the forms marked as localizable?

**Comment by gfue** [comment]
My bad - that indeed was the problem - mea culpa and thanks!
