### ISSUE TITLE
Can't update to v1.82

### ISSUE THREAD

**Issue by yankarinRG** [dotnet/ResXResourceManager#633]
When trying to update, the VSIX installer displays the following message:

> This extension is already installed to all applicable products.

When looking inside the .vsix file, I see that the version in extension.vsixmanifest is still 1.81.6225.0.
The version in ResXResourceManager/src/Directory.Build.props was changed to 1.82 in commit https://github.com/dotnet/ResXResourceManager/commit/cabe076e74c2031166ba872cb39d46d0a61a1718, but somehow this was not reflected in the final file?

**Comment by tom-englert** [comment]
use 1.83 to fix broken marketplace upload
