### ISSUE TITLE
Support for DeepL glossaries

### ISSUE THREAD

**Issue by jgraber** [dotnet/ResXResourceManager#639]
**Is your feature request related to a problem? Please describe.**
DeepL finnaly offers the use of a glossary that allows the users to use a set of pre-defined word pairs for the translation. That massively improves the translations for special words and terminology in a specific business context.  We use it for medical terms that are otherwise translated to completely unrelated words.

**Describe the solution you'd like**
 The glossaries can be saved in a DeepL account and used for translation requests. Therefore the source language and the glossary id have to be send as request parameters as shown in the API documentation:
https://developers.deepl.com/docs/api-reference/translate

 Is it possible to extend the DeepL section of the automatic translation function by adding the possibility to assign glossary Ids to the specific langauges we want to translate?

**Describe alternatives you've considered**
We could use the ResX scripting tool, export all ResX files and create our own translation tool for the DeepL  API. We would prefere not do go down that road then we like the built-in features of ResX Manager and think that other would profit from a solution directly in the ResX Manager.

**Additional context**
We would need an input field for each target language to set the glosary_id parameter and the neutral language we use in our application should be send with the request as the source_lang property.

**Comment by tom-englert** [comment]
Fixed by #642
