### ISSUE TITLE
Move to Resource menu option does not open ResX Resource Manager as shown in the documentation

### ISSUE THREAD

**Issue by FBUtveckling** [dotnet/ResXResourceManager#640]
Using the latest version (1.84) in Visual Studio 2022 and 2019, the Move to Resource menu option adds the string to the resources but does not open ResXManager when checking the Edit new entry in ResX Resource Manager.

It is necessary to open the editor manually and the replacement of the string with the reference code to the created resource is not obtained, as shown in the ResXManager documentation video.

**Comment by FBUtveckling** [comment]
It is required to have a resource file for language Neutral otherwise ResXManager will not activate.

Close.

**Comment by FBUtveckling** [comment]
Missing information in the documentation.

**Comment by tom-englert** [comment]
@FBUtveckling this is not a ResXManager specific topic, you will find this in Microsofts documentation about how resx resources work.
