### ISSUE TITLE
Support for .vsct files would be nice!

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/ResXResourceManager#643]
Basically the button text in these files: https://github.com/ErikEJ/EFCorePowerTools/tree/master/src/GUI/EFCorePowerTools

**Comment by tom-englert** [comment]
That would be a tough job, since .vsct and .resx have nothing in common.

A much simpler solution, that also avoids the need to maintain multiple .vsct files is this:
https://github.com/dotnet/ResXResourceManager/blob/d5651be61ddf2340311b36a0010016210787678a/src/ResXManager.VSIX/VSPackage.cs#L306

**Comment by ErikEJ** [comment]
Elegant!

**Comment by ErikEJ** [comment]
Looking at this, never knew there was a OleMenuCommand with the .Text property 😢

**Comment by ErikEJ** [comment]
Note to self: requires this CommandFlag for the Button in the .vsct file:

`<CommandFlag>TextChanges</CommandFlag>`
