### ISSUE TITLE
在.axaml(AvaloniaUi)文件增加“移动到资源”功能支持 Add support for "move to resource" feature in. axaml (AvaloniaUi) file

### ISSUE THREAD

**Issue by DaiYu-233** [dotnet/ResXResourceManager#645]
在.axaml文件增加“移动到资源”功能，像.xaml那样 

Add the "Move to Resource" feature to the. axaml file, similar to. xaml

**Comment by tom-englert** [comment]
Please provide an English translation

**Comment by DaiYu-233** [comment]
> Please provide an English translation
Add the "Move to Resource" feature to the. axaml file, similar to. xaml
