### ISSUE TITLE
Add ability to handle custom language (e.g. local dialect not listed in ISO language codes)

### ISSUE THREAD

**Issue by fraluderin** [dotnet/ResXResourceManager#651]
I'm currently developing an industrial human-machine interface with C# and WPF.
I've had always been using ResX Manager to handle localization in my projects, since it's lightweight and super easy to use.
My current project has an unusual requirement: to support a non-global language, more specifically a local italian dialect from north Italy. This is for an initiative which aims to preserve and pass on this dialect to new generations.
Obviously this dialect has no ISO language code.

I believe ResX Manager uses ISO language codes to recognize which resource files are in the solution and handle them.
For example, currently I have these files in my solution:

- Languages.resx
- Languages.it-IT.resx
- Languages.fr-FR.resx.

These three languages are properly handled by ResX Manager. I'd like to add a "custom language", something like so:

- Languages.LocalDialect.resx

I know this is a very niche requirement and I know I can't ask a real feature implementation for this, but I'm just wondering if you can put me in the right direction to achieve my goal, even with some tweaks or workaround - my biggest desire is not switching to any other localization tool and find a way to include this dialect in my languages.

Thank you for your help and your wonderful work with this extension!

**Comment by tom-englert** [comment]
The main question here is: If there is no ISO language, how would you use this language in your application? 
`CultureInfo.CurrentCulture = ?????`

**Comment by tom-englert** [comment]
Maybe this helps: #376

**Comment by tom-englert** [comment]
@fraluderin Did this work for you?
