### ISSUE TITLE
DeepL - API Key not overwriting old API Key

### ISSUE THREAD

**Issue by b1tzer0** [dotnet/ResXResourceManager#653]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
I originally had a DeepL api key, after refreshing my API Key on DeepL; I noticed that the API Key is not properly saving the new key, it always reverts back to the old key.

**To Reproduce**
- Steps to reproduce the behavior:
- Input API Key
- Check the Save Cred checkbox.
- Close Visual Studio

- Reopen Visual Studio
- Input New API Key
- Make sure the Save Cred checkbox is still checked
- Close Visual Studio

- Reopen Visual Studio
- Try to do a translation
- Get error 403
- Re-apply your API Key
- Try to do a translation again
- Success

**Expected behavior**
The new API Key should have been saved, overriding the old API Key.

**Comment by tom-englert** [comment]
I can't reproduce this. Maybe you closed VS while the focus was still in the text field, so it was not applied yet?

**Comment by tom-englert** [comment]
No response, closed as stale
