### ISSUE TITLE
Replace internal with public in property when generate Resources class

### ISSUE THREAD

**Issue by sqlite-me** [dotnet/ResXResourceManager#657]
**Is your feature request related to a problem? Please describe.**
ResXFileCodeGenerator generate Resources property is internal, it can not be used for wpf xaml, eg:{x:Static mainProp:Resources.ValidatingSelectLabwareNotifyMsg}

**Describe the solution you'd like**
Replace internal with public in property when generate Resources class

**Comment by tom-englert** [comment]
ResXFileCodeGenerator has nothing to do with ResXResourceManager, it's provided by VisualStudio and can be changed here:
![image](https://github.com/user-attachments/assets/10be3433-7fe2-4e48-a972-154898246026)

In ResXResourceManager you can change it here:
![image](https://github.com/user-attachments/assets/d4edae0e-5fbb-431d-be95-b90b2ff00d1e)
