### ISSUE TITLE
Unable to load version 1.86

### ISSUE THREAD

**Issue by chorec** [dotnet/ResXResourceManager#662]
When I click Resx manager it just doesn't show.
It worked properly up to version 1.85

--------------------------------
My version of Visual Studio
Microsoft Visual Studio Community 2022 (64-bit)
Version 17.8.2

**Comment by tom-englert** [comment]
https://github.com/dotnet/ResXResourceManager/blob/master/Documentation%2FTopics%2FTroubleshooting.md

**Comment by tom-englert** [comment]
Just tried with VS Version 17.11.3 and everything looks fine.
