### ISSUE TITLE
ResX manager keeps resetting / regenerating a translating file

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/ResXResourceManager#666]
**Describe the bug**

We have many resx and xliff files. However, just 1 of them is being regenerated by resetting all translations and changing everything back from French (FR) to English.

I've been chasing this issue for a while. The state is correctly set to `translated` in the XLIFF files.

I just took the time to compare this xliff file with all the others. What I found was that a few notes (`note` element in xliff, `comment` in resx) were missing. I manually copied these lines into the xliff and they start appearing in the resx as well.

This did not solve the issue though. Everything is being reset again from (FR) "translated" to EN "needs-review-translation". Somehow the synchronization thinks the xliff is outdated and needs to be synced from the resx file.

I will continue to update this ticket with my research.

**Comment by GeertvanHorrik** [comment]
Finally found the issue. One of the files (e.g. `MyTranslation.nl.xlf`) contained `target-language="fr"`, so it saw 2 different resource files for the same target language.

Would you like to throw an exception in such case or just assume it's user error?

**Comment by tom-englert** [comment]
Whatever helps you best to trace down such a problem. At least it should log an error in the output panel.
