### ISSUE TITLE
Rebuild Translate window | Add separated API Config tab

### ISSUE THREAD

**Issue by krzysztofrosol** [dotnet/ResXResourceManager#670]
**Translate Tab rebuild request**
Please move API configuration to separate tab.
Please change current configuration to simple dropdown to select preferred API.
Please remember my choices.

**Problem**
Look at attached screen. There is no room to quick translations when updating of resources. I have to enlarge this tool window.
![Image](https://github.com/user-attachments/assets/38a073be-ca55-4264-bc74-6c4161454768)

**Solution**
Look at attached screen. If you move configuration to separate tab, you will have a space to words to be translated.
![Image](https://github.com/user-attachments/assets/d4d884df-ab8f-46c0-a2ae-e855795b2283)

**Comment by tom-englert** [comment]
Happy to accept your PR with a better UI.

However you don't need to dock to the smallest available panel, then there is plenty of room left, even if you only have a small FHD monitor.

**Comment by krzysztofrosol** [comment]
Hi Tom, thank you for your reply. I am docking this panel not only for ResX. My project is already mature, so I have to debug a lot :/.
I am currently using ResX to add some resources and translate them into 2 languages that I only know exist ;)

**Comment by tom-englert** [comment]
You use RXRM for debugging?

**Comment by tom-englert** [comment]
5387f614a576ab6cc7cc875551d0072fbdaad2e5: Translator config can be collapsed
